. (Join-Path $PSScriptRoot 'Common.ps1')

$platform = Read-RepoFile 'rust-runtime\src\platform\mod.rs'
$platformLive = Read-RepoFile 'rust-runtime\src\platform\live.rs'
$platformVod = Read-RepoFile 'rust-runtime\src\platform\vod.rs'
$platformSoop = Read-RepoFile 'rust-runtime\src\platform\soop\mod.rs'
$platformSoopLive = Read-RepoFile 'rust-runtime\src\platform\soop\live.rs'
$platformSoopVod = Read-RepoFile 'rust-runtime\src\platform\soop\vod.rs'
$support = Read-RepoFile 'rust-runtime\src\support.rs'
$backend = Read-RepoFile 'rust-runtime\src\backend.rs'
$watcher = Read-RepoFile 'rust-runtime\src\native_watcher.rs'
$vodFacade = Read-RepoFile 'rust-runtime\src\vod.rs'
$queueService = Read-RepoFile 'rust-runtime\src\queue_service.rs'
$backupService = Read-RepoFile 'rust-runtime\src\backup_service.rs'
$storageService = Read-RepoFile 'rust-runtime\src\storage_service.rs'
$store = Read-RepoFile 'rust-runtime\src\store.rs'
$main = Read-RepoFile 'rust-runtime\src\main.rs'
$lib = Read-RepoFile 'rust-runtime\src\lib.rs'
$core = Read-RepoFile 'rust-runtime\src\app_core.rs'
$diagnostics = Read-RepoFile 'rust-runtime\src\diagnostics.rs'
$cli = Read-RepoFile 'rust-runtime\src\bin\stream-archive-cli.rs'
$guiManifest = Read-RepoFile 'rust-gui\Cargo.toml'
$guiMain = Read-RepoFile 'rust-gui\src\main.rs'
$guiUi = Read-RepoFile 'rust-gui\ui\app-window.slint'
$maintenanceUi = Read-RepoFile 'rust-gui\ui\maintenance.slint'
$guiSources = (Get-ChildItem (Join-Path $script:RuntimeContractsRoot 'rust-gui/src') -Filter '*.rs' -Recurse | ForEach-Object { Get-Content $_.FullName -Raw }) -join "`n"

# Phase 22.3 runtime/presentation boundary.
# The retained server binary is now a headless shared-core runtime entry. It must
# not reintroduce HTTP/Web presentation while preserving Queue/backup/history
# lifecycle startup and owned-runtime shutdown.
Assert-Match $main 'StreamArchiveCore::open\(&backend_dir\)' 'Headless runtime must bootstrap through StreamArchiveCore.'
Assert-Match $main 'core\.spawn_vod_history_sync\(\)' 'Headless runtime must keep VOD history synchronization.'
Assert-Match $main 'core\.spawn_auto_backup\(\)' 'Headless runtime must keep automatic backup scheduling.'
Assert-Match $main 'core\.spawn_queue_worker\(\)' 'Headless runtime must keep the persistent Queue worker.'
Assert-Match $main 'core\.shutdown\(\)\.await' 'Headless runtime must shut down through shared owned-runtime cleanup.'
Assert-NotMatch $main '\baxum::|Router::new|TcpListener::bind|include_str!\("\.\./web|STREAM_ARCHIVE_BIND|STREAM_ARCHIVE_TOKEN' 'Headless runtime must stay free of retired Web presentation/listener state.'

# SQLite is the only runtime configuration/history authority.
Assert-Match $main 'StreamArchiveCore::open\(&backend_dir\)' 'Headless startup must use the canonical shared core.'
Assert-Match $core 'Store::migrate_legacy_database\(&db_path\)' 'Shared core startup must perform only the bounded legacy database filename migration.'
Assert-Match $core 'Store::open\(db_path\)' 'Shared core startup must open the canonical SQLite store.'
Assert-Match $store 'const DATABASE_FILE:\s*&str\s*=\s*"stream-archive\.db"' 'Canonical database filename must use the Stream Archive namespace.'
Assert-Match $store 'STREAM_ARCHIVE_DATA_DIR' 'Data directory environment override must use the Stream Archive namespace.'
Assert-NotMatch $main 'bootstrap_primary_once|materialize_primary_files|SOOP_LIVE_SETTING\.ini|SOOP_LIVE_CHANNELS\.txt|SOOP_VOD_SETTING\.ini' 'Runtime must not import or emit legacy INI/TXT mirrors.'
Assert-NotMatch $store 'legacy-import-live|legacy-import-vod|read_safe_settings|read_channels|read_hidden_settings' 'SQLite store must not depend on legacy config-file import helpers.'
Assert-Match $store 'settings_cache: Arc<RwLock<BTreeMap<String, String>>>' 'Committed runtime settings cache is missing.'
Assert-RustTest $store 'runtime_config_cache_tracks_committed_writes' 'Committed settings-cache behavior test is missing.'
Assert-Match $store 'platform TEXT NOT NULL' 'Persistent history and queue schemas must retain platform identity.'
Assert-Match $queueService 'lifecycle_lock: Arc<Mutex<\(\)>>' 'Queue must share the global serialized VOD lifecycle lock.'

# Phase 21 shared service boundary. Presentation/authentication concerns must stay
# outside this facade so Slint and CLI callers can use Rust services directly.
Assert-Match $lib 'pub\s+mod\s+app_core' 'Shared library must expose the Phase 21 application core.'
Assert-Match $lib 'pub\s+mod\s+store' 'Shared library must expose canonical SQLite persistence.'
Assert-Match $lib 'pub\s+mod\s+backup_service' 'Shared library must expose the reusable backup service.'
Assert-Match $lib 'pub\s+mod\s+storage_service' 'Shared library must expose reusable storage diagnostics.'
Assert-Match $lib 'pub\s+mod\s+native_watcher' 'Shared library must expose the native watcher boundary.'
Assert-Match $lib 'pub\s+mod\s+vod' 'Shared library must expose the VOD facade.'
Assert-Match $core 'pub\s+struct\s+StreamArchiveCore' 'Phase 21 shared application facade is missing.'
Assert-Match $core 'Store::default_path\(&backend_dir\)' 'Shared core must open the canonical SQLite path.'
Assert-Match $core 'store::init_global\(store\.clone\(\)\)' 'Shared core must initialize the canonical global store for existing runtime modules.'
Assert-Match $core 'crate::environment_settings::validate_updates\(updates\)' 'Shared core environment settings writes must preserve canonical runtime validation.'
Assert-Match $core 'validate_setting_updates\(settings\)' 'Shared core provider settings writes must preserve runtime validation.'
Assert-Match $core 'validate_secret_updates\(secrets\)' 'Shared core provider secret writes must preserve security validation.'
Assert-Match $core 'protect_secret\(value\)' 'Shared core provider secret writes must use the native protection boundary.'
Assert-Match $core 'validate_channels\(channels\)' 'Shared core channel writes must preserve provider validation.'
Assert-Match $core 'apply_vod_tool_defaults' 'Shared core VOD operations must preserve canonical media-tool defaults.'
Assert-Match $core 'lifecycle_lock: Arc<Mutex<\(\)>>' 'Shared core must serialize VOD lifecycle operations.'
Assert-NotMatch $core 'pub\s+fn\s+(?:watcher|vod|queue|backups|config_write_lock|lifecycle_lock)\s*\(' 'Dead manager/lock compatibility getters must not return to the public core API.'
Assert-NotMatch $core 'pub\s+async\s+fn\s+(?:update_settings|update_secrets|update_vod_tool_settings)\s*\(' 'Dead generic configuration compatibility facades must not return to the public core API.'
Assert-NotMatch $core 'pub\s+fn\s+storage_check\s*\(' 'Unused single-path storage compatibility facade must not return to the public core API.'
Assert-Match $core 'pub\s+async\s+fn\s+shutdown' 'Shared core must expose owned-runtime shutdown.'
# Match actual Axum/direct http crate dependencies, not similarly named transport types such as reqwest::StatusCode.
Assert-NotMatch $core '(?m)^\s*use\s+(?:axum|http)(?:::|\s*\{)|\baxum::|\bhttp::(?:HeaderMap|StatusCode)\b' 'Shared core must stay independent from Axum/HTTP presentation concerns.'
Assert-RustTest $core 'assembled_core_keeps_one_canonical_store_backend_and_queue' 'Shared core canonical-store/queue regression test is missing.'
Assert-Match $core 'pub\s+async\s+fn\s+backup_snapshot' 'Shared core native backup snapshot service is missing.'
Assert-Match $core 'pub\s+async\s+fn\s+restore_backup' 'Shared core native restore service is missing.'
Assert-Match $core 'pub\s+fn\s+storage_snapshot' 'Shared core native storage snapshot service is missing.'
Assert-Match $storageService 'MIN_FREE_SPACE_GB' 'Shared storage diagnostics must use the canonical free-space threshold.'
Assert-Match $storageService 'channel\.outdir' 'Shared storage diagnostics must include channel-specific output directories.'
Assert-Match $core 'storage_service::snapshot\(&self\.store\)' 'Shared core storage diagnostics must delegate to the storage service.'
Assert-Match $core 'pub\s+async\s+fn\s+runtime_logs' 'Shared core bounded runtime log service is missing.'
Assert-Match $backupService 'pub\s+struct\s+BackupManager' 'Reusable backup manager is missing from backup_service.rs.'
Assert-Match $backupService 'pre_restore' 'Restore safety backup behavior is missing from shared backup service.'
Assert-NotMatch $backupService '\baxum::|HeaderMap|StatusCode|State\(' 'Shared backup service must stay independent from Axum/Web presentation.'

# Phase 21.2 Windows Slint shell. The desktop UI is a presentation adapter over
# StreamArchiveCore, not another HTTP client, persistence authority, or process owner.
Assert-Match $guiManifest 'name\s*=\s*"stream-archive-gui"' 'Slint desktop crate is missing.'
Assert-Match $guiManifest 'slint\s*=\s*\{' 'Slint runtime dependency is missing.'
Assert-Match $guiManifest 'stream-archive-server\s*=\s*\{\s*path\s*=\s*"\.\./rust-runtime"' 'Slint desktop must depend on the shared Rust library directly.'
Assert-Match $guiSources 'StreamArchiveCore' 'Slint bootstrap must use the shared application core.'
Assert-Match $guiSources 'resolve_backend_dir' 'Slint bootstrap must reuse canonical backend resolution.'
Assert-Match $backend '(?s)env::current_exe\(\).*?candidates\.push\(exe_dir\.join\("backend"\)\).*?env::current_dir\(\)' 'Portable backend resolution must prefer the executable-adjacent backend before the working directory.'
Assert-Match $guiSources 'bind_core_snapshot' 'Slint shell must bind runtime state from the shared core.'
Assert-NotMatch $guiSources '\breqwest::|\baxum::|https?://127\.0\.0\.1|https?://localhost|rusqlite::|Command::new|taskkill|pkill|killall' 'Slint shell must not bypass shared core through HTTP, SQLite, or direct process control.'
Assert-Match $guiUi 'export\s+global\s+AppState' 'Slint shell state boundary is missing.'
Assert-Match $guiUi 'callback\s+refresh-requested' 'Slint runtime refresh callback is missing.'
foreach ($page in @('LIVE', 'VOD', 'Queue', 'History', 'Settings')) {
    Assert-Match $guiUi ([regex]::Escape("page: `"$page`"")) "Slint navigation page missing: $page"
}
Assert-NotMatch $guiUi 'page:\s*"Maintenance"' 'Maintenance must stay nested under Settings rather than return as a top-level navigation page.'
Assert-NotMatch $guiUi 'page:\s*"Dashboard"' 'Dashboard must stay removed; its information is available through Settings diagnostics.'
Assert-Match $guiUi 'settings-view:\s*"General"' 'Settings must own an internal General/Manage view boundary.'
Assert-Match $guiUi 'settings-view\s*==\s*"Manage"' 'Settings must expose the nested management view.'
Assert-Match $guiUi 'MaintenancePage\s*\{' 'Backup/restore/diagnostics/logs must remain reachable inside Settings.'
Assert-Match $guiUi 'active-page:\s*"LIVE"' 'Configured native startup must default to the LIVE page.'

# Provider registry/facades.
Assert-Match $platform 'pub\s+mod\s+live' 'Platform LIVE facade must be registered.'
Assert-Match $platform 'pub\s+mod\s+vod' 'Platform VOD facade must be registered.'
Assert-Match $platform 'pub\s+mod\s+soop' 'SOOP provider module must be registered.'
Assert-Match $platform 'trait\s+PlatformProvider' 'Platform provider boundary is missing.'
Assert-Match $platform 'fn\s+detect_vod_platform' 'Platform registry must own VOD platform detection.'
Assert-Match $platformSoop 'pub\s+mod\s+live' 'SOOP LIVE provider must be registered.'
Assert-Match $platformSoop 'pub\s+mod\s+vod' 'SOOP VOD provider must be registered.'
Assert-Match $platformSoop 'fn\s+accepts_vod_url' 'SOOP provider must own SOOP VOD URL recognition.'
Assert-Match $platformLive 'enum\s+LiveSession' 'Common LIVE session facade is missing.'
Assert-Match $platformVod 'pub\s+struct\s+VodManager' 'Common VOD manager facade is missing.'
Assert-Match $support 'provider\(platform\)' 'Channel lookup must route through the platform provider.'

# Provider-specific network/auth details must stay below the platform boundary.
Assert-NotMatch $watcher 'https?://[^\s"'']*sooplive\.com|player_live_api\.php|LoginAction\.php' 'Native watcher must not contain direct SOOP network endpoints.'
Assert-Match $platformSoopLive 'player_live_api\.php' 'SOOP LIVE provider must own SOOP live discovery endpoints.'
Assert-NotMatch $vodFacade 'sooplive\.com|CloudFront|yt-dlp|ffmpeg|taskkill\.exe' 'Root VOD facade must stay platform/process neutral.'
Assert-NotMatch $platformVod 'CloudFront|private_auth\.php|LoginAction\.php|player_live_api\.php' 'Common VOD facade must not own provider network/auth implementation details.'
Assert-Match $platformSoopVod 'private_auth\.php' 'SOOP VOD provider must own SOOP authorization.'
Assert-Match $platformSoopVod 'vod\.sooplive\.com' 'SOOP VOD provider must own SOOP VOD endpoints.'

# Queue/orchestration may identify a provider and include routing fixtures in tests,
# but must not contain provider authentication/network implementation.
Assert-Match $queueService 'detect_vod_platform' 'VOD queue must persist detected platform identity.'
Assert-NotMatch $queueService 'CloudFront|private_auth\.php|LoginAction\.php|player_live_api\.php' 'VOD queue must remain provider-neutral.'

Write-Host 'Architecture contracts passed.'

# Phase 21.3: inspect every GUI module, not only the small bootstrap.
Assert-Match $core 'pub\s+async\s+fn\s+update_environment_settings' 'Native settings must persist through shared core.'
Assert-Match $core 'pub\s+fn\s+diagnostics' 'Structured diagnostics service is missing.'
Assert-Match $core 'pub\s+fn\s+is_first_run_unconfigured' 'Shared core must expose first-run routing state.'
Assert-Match $guiSources 'core\.is_first_run_unconfigured\(' 'Native startup must determine first-run routing through the shared core.'
Assert-Match $guiSources 'core\.update_environment_settings' 'GUI settings bypass shared service.'
Assert-Match $guiSources 'core\.diagnostics\(' 'GUI diagnostics must consume shared diagnostics.'
Assert-Match $diagnostics 'pub\s+enum\s+DiagnosticRequirement' 'Shared preflight must model Required/Optional/Informational checks.'
Assert-Match $diagnostics 'pub\s+struct\s+DiagnosticsSummary' 'Shared preflight summary model is missing.'
Assert-Match $diagnostics '"database\.integrity"' 'Shared preflight must retain stable database integrity check identity.'
Assert-Match $diagnostics '"provider\.soop"' 'Shared preflight must retain stable SOOP readiness identity.'
Assert-Match $diagnostics '"provider\.chzzk"' 'Shared preflight must retain stable CHZZK readiness identity.'
Assert-Match $diagnostics 'PRAGMA quick_check' 'Shared preflight must perform read-only SQLite integrity checking.'
Assert-Match $diagnostics 'blocking_errors\s*==\s*0' 'Runtime usability must depend on blocking required errors, not warnings.'
Assert-NotMatch $diagnostics '\breqwest::|https?://|Command::new|unprotect_secret' 'Shared preflight must remain local/read-only without provider network, subprocess, or secret-value reads.'
Assert-Match $cli 'collect_with_backup_and_secrets' 'CLI doctor must consume the same shared preflight model as Native Diagnostics.'
Assert-Match $cli 'doctor \[--json\]' 'CLI doctor must retain documented JSON automation mode.'
Assert-NotMatch $guiSources 'std::fs::write|fs::write|Connection::open|std::process|tokio::process' 'GUI must not write runtime files or own child processes.'
Assert-Match $maintenanceUi 'Phase 23\.2: Native Diagnostics renders the shared read-only runtime preflight\.' 'Shared read-only preflight must live in the nested Settings management view.'
Assert-Match $maintenanceUi 'section\s*==\s*"Diagnostics"' 'Nested Settings management must retain the Diagnostics section.'
Assert-Match $maintenanceUi 'MaintenanceState\.diagnostic-rows' 'Nested Settings management diagnostics must render shared diagnostic rows.'
Assert-Match $guiSources 'core\.backup_snapshot\(' 'Native Maintenance must load backups through StreamArchiveCore.'
Assert-Match $guiSources 'core\.restore_backup\(' 'Native Maintenance restore must use StreamArchiveCore.'
Assert-Match $guiSources 'core\.runtime_logs\(' 'Native log viewer must use the bounded shared LogBuffer service.'
Assert-Match $guiSources 'core\.storage_snapshot\(' 'Native storage diagnostics must use StreamArchiveCore.'
Assert-NotMatch $guiUi 'MaintenanceState\.save-backup-policy\(' 'General settings must not duplicate backup policy actions.'
Assert-NotMatch $guiUi 'MaintenanceState\.backup-directory' 'General settings must not duplicate backup policy fields.'
Assert-Match $maintenanceUi 'Phase 21\.9: Settings > Manage owns backup policy and operations\.' 'Nested Settings management must own backup policy presentation.'
Assert-Match $maintenanceUi 'MaintenanceState\.save-backup-policy\(' 'Nested Settings management must save backup policy through the shared MaintenanceState callback.'
Assert-Match $maintenanceUi 'MaintenanceState\.backup-directory' 'Nested Settings management must bind the shared backup directory policy.'
Assert-Match $maintenanceUi 'MaintenanceState\.create-backup\(' 'Nested Settings management must retain operational backup creation.'
Assert-Match $maintenanceUi 'MaintenanceState\.request-restore\(' 'Nested Settings management must retain operational restore actions.'
Assert-NotMatch $guiSources '\bSha256::new\b|\bsha2::Digest\b|\bread_to_end\s*\(|\bstd::io::copy\s*\(' 'Slint presentation must not implement backup hashing/copying.'
