. (Join-Path $PSScriptRoot 'Common.ps1')

$recorder = Read-RepoFile 'rust-web/src/recorder.rs'
$watcher = Read-RepoFile 'rust-web/src/native_watcher.rs'
$vodFacade = Read-RepoFile 'rust-web/src/vod.rs'
$soopVod = Read-RepoFile 'rust-web/src/platform/soop/vod.rs'
$chzzkVod = Read-RepoFile 'rust-web/src/platform/chzzk/vod.rs'
$runtime = Read-RepoFile 'rust-web/src/platform_runtime.rs'
$allRuntime = $recorder + $soopVod + $chzzkVod + $runtime

Assert-Match $recorder '\.kill_on_drop\(true\)' 'LIVE Streamlink child must retain kill-on-drop fallback.'
Assert-NotMatch $vodFacade 'taskkill\.exe|yt-dlp|ffmpeg|sooplive\.com' 'Root VOD facade must remain provider/process neutral.'
Assert-Match $chzzkVod 'terminate_owned\(&mut streamlink_child\)\.await' 'CHZZK VOD setup/failure paths must terminate owned Streamlink.'
Assert-Match $chzzkVod 'terminate_owned\(&mut ffmpeg_child\)\.await' 'CHZZK VOD cancellation must terminate owned FFmpeg.'
Assert-Match $chzzkVod 'abort_reader_tasks\(reader_tasks\)\.await' 'CHZZK VOD cancellation must reap line readers.'
Assert-Match $chzzkVod 'drain_failed_reader_tasks\(' 'CHZZK VOD process failures must drain bounded stderr readers before reporting the error.'
Assert-Match $chzzkVod 'join_reader_tasks\(tasks\)\.await' 'CHZZK VOD reader tasks must be joined after draining.'
Assert-Match $chzzkVod 'mpsc::channel::<String>\(256\)' 'External-tool line transport must remain bounded.'
Assert-Match $runtime 'async fn terminate_owned\(child: &mut Child\)' 'Common owned-process termination primitive is missing.'
Assert-Match $runtime 'struct OwnedProcessTree' 'Durable retained owned-tree type is missing.'
Assert-Match $runtime 'JOB_OBJECT_LIMIT_KILL_ON_JOB_CLOSE' 'Windows retained process tree must use kill-on-close Job ownership.'
Assert-Match $runtime 'AssignProcessToJobObject' 'Windows retained process tree must assign owned members to the Job.'
Assert-Match $runtime 'TerminateJobObject' 'Windows retained process tree must have an authoritative tree-termination primitive.'
Assert-Match $runtime 'QueryInformationJobObject' 'Retained Job cleanup must query the Job directly rather than infer liveness from a historical root PID.'
Assert-Match $runtime 'ActiveProcesses' 'Retained Job cleanup must verify that no Job members remain before returning.'
Assert-Match $runtime 'self\.job\.active_process_count\(\)' 'Retained Job cleanup must loop on authoritative Job membership.'
Assert-NotMatch $runtime 'self\.root_pid' 'Retained process ownership must not reuse a historical root PID after spawn.'
Assert-Match $runtime 'CreateToolhelp32Snapshot' 'Windows owned-tree capture must discover already-existing descendants.'
Assert-Match $runtime 'child\.raw_handle\(\)' 'Windows retained ownership must start from the exact spawned Child process handle.'
Assert-Match $runtime 'GetProcessTimes' 'Windows PID-based descendant absorption must pin process creation identity.'
Assert-Match $runtime 'struct ProcessIdentity' 'Windows snapshot assignments must carry stable process identity.'
Assert-Match $runtime 'capture_child\(child: &Child\)' 'Windows Job capture must accept the spawned Child handle rather than a PID alone.'
Assert-Match $runtime 'assign_handle\(root_handle\)' 'Windows Job capture must assign the exact spawned root handle before descendant absorption.'
Assert-Match $runtime 'query_identity\(root\.pid\)\? != Some\(root\)' 'Windows snapshot traversal must stop when the numeric root PID no longer matches its creation identity.'
Assert-Match $recorder 'owned_tree:\s*OwnedProcessTree' 'Recording must retain durable process-tree ownership for its whole lifetime.'
Assert-Match $recorder 'OwnedProcessTree::capture\(&child\)' 'LIVE recorder must capture durable tree ownership immediately after spawn from the exact Child handle.'
Assert-NotMatch $recorder 'OwnedProcessTree::capture\(pid\)' 'LIVE recorder must never establish retained ownership from a reusable numeric PID alone.'
Assert-Match $recorder 'rec\.owned_tree\s*\.terminate_now\(\)' 'Root-exit polling must enforce retained-tree cleanup before Recording can be dropped.'
Assert-Match $recorder 'rec\.owned_tree\s*\.terminate\(&mut rec\.child\)' 'Recorder stop must always terminate through retained tree ownership, including after root exit.'
Assert-NotMatch $recorder 'if rec\.child\.try_wait\(\)\?\.is_none\(\)\s*\{\s*return terminate_owned_checked' 'Recorder stop must not bypass retained-tree cleanup when the root is already reaped.'
Assert-Match $watcher 'state\.recording\s*=\s*Some\(rec\)' 'Watcher must retain the Recording owner if checked cleanup returns an unexpected error.'
Assert-Match $watcher 'channel removal deferred while recorder cleanup is retained' 'Removed channels must remain tracked if recorder cleanup returns an unexpected error.'
Assert-RustTest $runtime 'owned_child_is_terminated_and_reaped' 'Owned-child termination/reaping behavior test is missing.'
Assert-RustTest $runtime 'windows_retained_tree_owner_survives_root_exit' 'Windows retained-owner root-exit failure-path test is missing.'
Assert-Match $runtime 'child_snapshot_rejects_wrong_creation_identity' 'Windows retained-owner test must exercise root creation-identity mismatch rejection.'
Assert-Match $runtime 'taskkill\.exe' 'Windows exact-PID tree fallback for non-retained callers is missing.'
Assert-Match $runtime '\.arg\("/PID"\)' 'Windows non-retained termination fallback must target the owned PID.'
Assert-Match $runtime '\.arg\("/T"\)' 'Windows non-retained termination fallback must include descendants.'
Assert-Match $runtime '\.arg\("/F"\)' 'Windows non-retained termination fallback must force cleanup when required.'
Assert-NotMatch $allRuntime '(?i)taskkill(?:\.exe)?[^\r\n]*(?:/IM|\.arg\("/IM"\))' 'Process-name-wide taskkill /IM is forbidden.'
Assert-NotMatch ($recorder + $soopVod + $chzzkVod) 'taskkill\.exe' 'Provider/runtime callers must use the common process boundary.'

$stopCalls = [regex]::Matches($soopVod, 'stop_child\(&mut child\)\.await;').Count
if ($stopCalls -lt 2) { throw "SOOP VOD cancellation must cover progress and capture children; found $stopCalls call(s)." }
Assert-Match $soopVod 'if !exit\.success\(\)' 'SOOP capture must reject non-zero exits.'
Assert-Match $soopVod 'if exit\.success\(\)' 'SOOP progress must distinguish successful exits.'
Write-Host 'Process lifecycle contracts passed.'
