. (Join-Path $PSScriptRoot 'Common.ps1')

$backend = Read-RepoFile 'rust-runtime/src/backend.rs'
$security = Read-RepoFile 'rust-runtime/src/security.rs'
$auth = Read-RepoFile 'rust-runtime/src/platform/chzzk/auth.rs'
$chzzkVod = Read-RepoFile 'rust-runtime/src/platform/chzzk/vod.rs'
$recorder = Read-RepoFile 'rust-runtime/src/recorder.rs'
$runtime = Read-RepoFile 'rust-runtime/src/platform_runtime.rs'

Assert-Match $backend '"CHZZK_NID_AUT"' 'NID_AUT must remain a hidden setting.'
Assert-Match $backend '"CHZZK_NID_SES"' 'NID_SES must remain a hidden setting.'
Assert-Match $auth 'unprotect_secret' 'CHZZK auth must use the common encrypted secret boundary.'
Assert-Match $security 'CryptProtectData' 'Windows secret protection must remain DPAPI-backed.'
Assert-Match $security 'DPAPI_PREFIX' 'Windows DPAPI payload prefix must remain explicit.'
Assert-Match $security 'NATIVE_SECRET_PREFIX' 'Unix native secret references must use an explicit versioned prefix.'
Assert-Match $security 'native-secret:v1:' 'Unix native secret reference format must remain versioned.'
Assert-Match $security 'Command::new\("secret-tool"\)' 'Linux secret storage must use the Secret Service helper boundary.'
Assert-Match $security '\.stdin\(Stdio::piped\(\)\)' 'Linux Secret Service writes must pass secret data through stdin.'
Assert-Match $security 'const APPLICATION_ATTRIBUTE: &str = "stream-archive"' 'Linux Secret Service entries must remain Stream Archive scoped.'
Assert-Match $security '"application"' 'Linux Secret Service lookup/store must use an application attribute.'
Assert-Match $security 'SecKeychainAddGenericPassword' 'macOS secret storage must use Keychain Services.'
Assert-Match $security 'SecKeychainFindGenericPassword' 'macOS secret lookup must use Keychain Services.'
Assert-Match $security 'io\.github\.p1k1g\.stream-archive' 'macOS Keychain entries must remain app-scoped.'
Assert-NotMatch $security '\.arg\(value\)|\.args\([^\)]*value' 'Linux secret values must never be appended to helper argv.'
Assert-Match $security 'New writes never intentionally fall back to plaintext' 'Secret writes must fail closed instead of silently storing plaintext.'
Assert-Match $chzzkVod 'ChzzkAuth::load\(\)' 'CHZZK VOD must reuse encrypted CHZZK auth.'
Assert-Match $chzzkVod 'chzzk-cookies\.txt' 'CHZZK VOD must use temporary cookie-file transport.'
Assert-Match $chzzkVod 'restrict_private_dir\(&preparing\)' 'CHZZK VOD must invoke the platform private-directory boundary.'
Assert-Match $runtime 'icacls\.exe' 'Windows private-directory implementation must use ACL tooling.'
Assert-Match $runtime '/inheritance:r' 'Windows private directories must remove inherited permissions.'
Assert-Match $runtime '\(OI\)\(CI\)F' 'Windows private directories must grant the current owner required access.'
Assert-Match $runtime 'from_mode\(0o700\)' 'Unix private directories must use mode 0700.'
Assert-NotMatch ($chzzkVod + $recorder) '--http-cookie\s+NID_|NID_AUT=.*--|NID_SES=.*--' 'CHZZK secrets must not appear directly in process arguments.'
Assert-Match $chzzkVod 'NID_\(\?:AUT\|SES\)' 'CHZZK VOD logs/errors must redact Naver cookie values.'
Write-Host 'Security contracts passed.'
