. (Join-Path $PSScriptRoot 'Common.ps1')

$platform = Read-RepoFile 'rust-web/src/platform/mod.rs'
$chzzk = Read-RepoFile 'rust-web/src/platform/chzzk/mod.rs'
$vodFacade = Read-RepoFile 'rust-web/src/platform/vod.rs'
$chzzkVod = Read-RepoFile 'rust-web/src/platform/chzzk/vod.rs'
$queue = Read-RepoFile 'rust-web/src/vod_queue.rs'
$queueService = Read-RepoFile 'rust-web/src/queue_service.rs'
$auth = Read-RepoFile 'rust-web/src/platform/chzzk/auth.rs'
$recorder = Read-RepoFile 'rust-web/src/recorder.rs'
$main = Read-RepoFile 'rust-web/src/main.rs'
$runtime = Read-RepoFile 'rust-web/src/platform_runtime.rs'
$workflow = Read-RepoFile '.github/workflows/rust-web-check.yml'

# Platform registration / URL routing.
Assert-Match $chzzk 'pub mod vod;' 'CHZZK VOD provider module is not registered.'
Assert-Match $chzzk 'vod:\s*true' 'CHZZK VOD capability is not enabled.'
Assert-Match $chzzk 'chzzk\.naver\.com' 'CHZZK provider does not validate the VOD host.'
Assert-Match $chzzk 'parts\[0\] == "video"' 'CHZZK /video/<id> URL recognition is missing.'
Assert-Match $platform 'detects_soop_and_chzzk_vod_urls' 'Platform VOD routing regression coverage is missing.'

# Common queue/API orchestration must dispatch through the provider-neutral facade.
Assert-Match $vodFacade 'chzzk:\s*chzzk::vod::VodManager' 'Common VOD facade does not own a CHZZK provider manager.'
Assert-Match $vodFacade 'PlatformId::Chzzk\s*=>\s*self\.chzzk\.analyze' 'CHZZK analyze is not routed through the common VOD facade.'
Assert-Match $vodFacade 'PlatformId::Chzzk\s*=>\s*self\.chzzk\.download' 'CHZZK download is not routed through the common VOD facade.'
Assert-Match $vodFacade 'PlatformId::Chzzk\s*=>\s*chzzk::vod::validate_download_request' 'CHZZK queue validation is not provider-routed.'
Assert-Match $vodFacade 'lifecycle:\s*Mutex<\(\)>' 'Common VOD facade does not serialize provider starts.'
Assert-Match $vodFacade 'ensure_idle\(\)\.await\?' 'Cross-provider VOD start guard is missing.'
Assert-Match $vodFacade 'running_provider\(\)' 'VOD status/cancel cannot recover the actually running provider.'
Assert-NotMatch ($queue + "`n" + $queueService) 'api\.chzzk\.naver\.com|NID_AUT|NID_SES' 'Provider-specific CHZZK network/auth logic leaked into Queue orchestration.'

# Existing CHZZK auth encrypted CHZZK auth must be reused; plaintext temp data is private and scavenged.
Assert-Match $chzzkVod 'ChzzkAuth::load\(\)' 'CHZZK VOD does not reuse the encrypted CHZZK auth authentication store.'
Assert-Match $chzzkVod 'chzzk-cookies\.txt' 'CHZZK VOD temporary Netscape cookie transport is missing.'
Assert-Match $chzzkVod 'JobDirGuard' 'CHZZK VOD temporary job/cookie cleanup guard is missing.'
Assert-Match $chzzkVod 'cleanup_stale_job_dirs' 'Stale CHZZK VOD job directory scavenging is missing.'
Assert-Match $chzzkVod 'restrict_private_dir' 'CHZZK VOD temporary directory permission hardening is missing.'
Assert-Match $runtime 'icacls\.exe' 'Windows current-user-only CHZZK temp ACL setup is missing.'
Assert-Match $chzzkVod 'NID_\(\?:AUT\|SES\)' 'CHZZK VOD secret redaction coverage is missing.'
Assert-NotMatch $chzzkVod 'NID_AUT=.*--|NID_SES=.*--' 'CHZZK cookies must not be put directly on process arguments.'
Assert-Match $auth 'CHZZK_NID_AUT' 'Shared CHZZK auth key disappeared.'
Assert-Match $auth 'CHZZK_NID_SES' 'Shared CHZZK auth key disappeared.'

# Listener bind remains defense-in-depth, but backend/job ownership must not depend on a port.
Assert-Match $main 'TcpListener::bind\(&bind\)[\s\S]*?VodManager::new\(backend_dir\.clone\(\), logs\.clone\(\)\)' 'Early server bind defense-in-depth ordering disappeared.'

# Per-job OS locking is the source of truth for active CHZZK temp ownership.
Assert-Match $chzzkVod 'use fs2::FileExt;' 'CHZZK VOD per-job OS locking is missing.'
Assert-Match $chzzkVod 'JOB_LOCK_FILE_NAME:\s*&str\s*=\s*"owner\.lock"' 'CHZZK VOD ownership lock filename is missing.'
Assert-Match $chzzkVod 'lock\.lock_exclusive\(\)' 'CHZZK VOD job does not acquire an exclusive ownership lock.'
Assert-Match $chzzkVod 'try_lock_exclusive\(\)' 'Stale cleanup does not probe ownership locks before deleting job directories.'
Assert-Match $chzzkVod 'FileExt::unlock\(&self\.lock\)' 'CHZZK VOD job guard does not release its ownership lock on teardown.'
Assert-Match $chzzkVod 'name == COOKIE_FILE_NAME \|\| name == JOB_LOCK_FILE_NAME' 'Retry/cancel cleanup must preserve both cookie and ownership lock files.'
Assert-Match $chzzkVod 'active_job_lock_survives_scavenging_until_release' 'Active-owner stale-cleanup regression test is missing.'

# CHZZK metadata comes from CHZZK API; Streamlink owns DASH extraction/mux and the VOD-owned FFmpeg finalizes TS with media progress.
Assert-Match $chzzkVod 'struct ChzzkTools' 'CHZZK Streamlink tool bundle is missing.'
Assert-Match $chzzkVod 'api\.chzzk\.naver\.com/service/v3/videos/' 'CHZZK VOD metadata is not read from the CHZZK API.'
Assert-NotMatch $chzzkVod 'duration_seconds[\s\S]*?/ 1000;' 'CHZZK API duration is already seconds and must not be divided by 1000.'
Assert-Match $chzzkVod 'chzzk_api_metadata_preserves_seconds' 'CHZZK API seconds regression test is missing.'
Assert-Match $chzzkVod 'MEDIA_FILE_NAME:\s*&str\s*=\s*"media\.ts"' 'CHZZK VOD short MPEG-TS staging filename is missing.'
Assert-Match $chzzkVod 'claim_collision_path\(&output_dir,\s*&base,\s*"ts"\)' 'CHZZK VOD final output is not MPEG-TS.'
Assert-Match $chzzkVod 'staging_output\s*=\s*job_dir\.join\(MEDIA_FILE_NAME\)' 'CHZZK VOD does not write into its private short staging path.'
Assert-Match $chzzkVod 'finalize_output\(&staged_file,\s*&destination,\s*cancel\)' 'CHZZK VOD staging output is not finalized through the claimed destination.'
Assert-Match $chzzkVod 'cleanup_job_media' 'CHZZK VOD retry/cancel cleanup is not scoped to the owned job directory.'
Assert-Match $chzzkVod 'resolve_streamlink_tool' 'CHZZK VOD Streamlink resolver is missing.'
Assert-Match $chzzkVod 'STREAMLINK_PATH' 'CHZZK VOD does not honor the configured Streamlink path.'
Assert-Match $chzzkVod '"--json"' 'CHZZK VOD Streamlink quality analysis is missing.'
Assert-Match $chzzkVod '"--http-cookies-file"' 'CHZZK VOD Streamlink cookie transport is missing.'
Assert-Match $chzzkVod '"--ffmpeg-ffmpeg"' 'CHZZK VOD does not provide FFmpeg to Streamlink.'
Assert-Match $chzzkVod '"--ffmpeg-fout"' 'CHZZK VOD does not force Streamlink DASH mux output format.'
Assert-Match $chzzkVod '"mpegts"' 'CHZZK VOD Streamlink DASH mux is not forced to MPEG-TS.'
Assert-Match $chzzkVod '"--stdout"' 'CHZZK VOD Streamlink MPEG-TS pipe is missing.'
Assert-Match $chzzkVod '"-progress"' 'CHZZK VOD owned FFmpeg progress output is missing.'
Assert-Match $chzzkVod '"pipe:1"' 'CHZZK VOD FFmpeg progress pipe is missing.'
Assert-Match $chzzkVod 'ffmpeg_progress_seconds' 'CHZZK VOD FFmpeg media progress parser is missing.'
Assert-Match $chzzkVod 'ffmpeg_media_progress_drives_chzzk_percent_and_time' 'CHZZK VOD progress regression test is missing.'
Assert-Match $recorder 'pub\(crate\) fn timestamp_rebase_player_args' 'CHZZK LIVE MPEG-TS player helper disappeared.'
Assert-Match $recorder '-f mpegts' 'Shared CHZZK player pipeline no longer emits MPEG-TS.'
Assert-Match $recorder '-c copy' 'Shared CHZZK player pipeline is no longer stream-copy only.'
Assert-Match $chzzkVod 'streamlink_json_builds_quality_options' 'CHZZK Streamlink quality regression test is missing.'
Assert-Match $chzzkVod 'maps_legacy_height_quality_to_streamlink_selector' 'CHZZK legacy quality mapping regression test is missing.'
Assert-NotMatch $chzzkVod '"--dump-single-json"|"--merge-output-format"|run_ffmpeg_fallback|is_source_url_extractor_bug|tools\.yt_dlp' 'Legacy CHZZK yt-dlp/direct-DASH fallback code returned.'
Assert-Match $runtime 'taskkill\.exe' 'Windows owned-process cancellation path is missing.'
Assert-Match $chzzkVod 'spawn_owned\(&mut ffmpeg_command\)' 'Downstream FFmpeg must establish retained ownership before execution.'
Assert-Match $chzzkVod 'streamlink_tree\.terminate\(&mut streamlink_child\)' 'Streamlink retained tree must be explicitly terminated on downstream setup failures.'
Assert-Match $runtime '\.arg\("/PID"\)' 'CHZZK VOD cancellation is not PID scoped.'
Assert-Match $runtime '\.arg\("/T"\)' 'CHZZK VOD cancellation does not include the owned child tree.'
Assert-NotMatch ($chzzkVod + $runtime) 'taskkill[^\r\n]*/IM' 'CHZZK VOD must never kill processes by image name.'

# Destination claims and cross-volume publication must be no-clobber, cancellable and crash-recoverable.
Assert-Match $chzzkVod 'DESTINATION_CLAIM_SUFFIX:\s*&str\s*=\s*"\.stream-archive\.claim"' 'Destination claim sidecar is missing.'
Assert-Match $chzzkVod 'FINALIZING_SUFFIX:\s*&str\s*=\s*"\.stream-archive\.finalizing"' 'Exact app-owned finalizing suffix is missing.'
Assert-Match $chzzkVod 'claim_collision_path' 'Atomic destination claim helper is missing.'
Assert-Match $chzzkVod 'lock\.try_lock_exclusive\(\)' 'Destination filename claim is not protected by an OS lock.'
Assert-Match $chzzkVod 'reusable lock anchor' 'Destination claim sidecars must remain reusable lock anchors after release.'
Assert-NotMatch $chzzkVod 'remove_file\(&self\.claim_path\)' 'Destination claim teardown must not unlink the reusable lock anchor.'
Assert-Match $chzzkVod 'finalizing_path' 'Destination-side atomic publication temp path is missing.'
Assert-Match $chzzkVod 'COPY_BUFFER_SIZE' 'Cancellable bounded copy buffer is missing.'
Assert-Match $chzzkVod 'cancel\.load\(Ordering::SeqCst\)' 'Cross-volume publication does not observe cancellation.'
Assert-Match $chzzkVod 'sync_all\(\)' 'Destination-side copied media is not synced before publication.'
Assert-Match $chzzkVod 'publish_by_copy' 'Cross-volume atomic publication helper is missing.'
Assert-Match $chzzkVod 'fs::hard_link\(' 'Final publication must use an atomic no-replace primitive.'
Assert-Match $chzzkVod 'PublishOutcome::Collision' 'Late external destination collisions must be detected without clobbering.'
Assert-NotMatch $chzzkVod 'fs::copy\(source,\s*target\)' 'CHZZK VOD must never copy directly into the final pathname.'
Assert-Match $chzzkVod 'should_mark_cancelled' 'Late cancellation completion precedence helper is missing.'
Assert-Match $chzzkVod 'state != "COMPLETED"' 'A successfully published file must remain COMPLETED after a late cancellation.'
Assert-Match $chzzkVod 'concurrent_destination_claims_choose_distinct_collision_paths' 'Concurrent destination claim regression test is missing.'
Assert-Match $chzzkVod 'destination_claim_sidecar_is_reused_after_release' 'Reusable destination-claim sidecar regression test is missing.'
Assert-Match $chzzkVod 'late_external_collision_is_not_clobbered_and_retargets' 'Late external no-clobber collision regression test is missing.'
Assert-Match $chzzkVod 'cancelled_copy_publish_keeps_final_unpublished' 'Cancelled destination publication regression test is missing.'
Assert-Match $chzzkVod 'completed_state_wins_over_late_cancellation' 'COMPLETED-versus-late-cancel regression test is missing.'
Assert-Match $chzzkVod 'stale_finalizing_is_reclaimed_under_destination_claim' 'Stale finalizing reclamation regression test is missing.'
Assert-Match $chzzkVod 'atomic_copy_publish_keeps_partial_data_out_of_final_name' 'Atomic publication success regression test is missing.'

# CHZZK API metadata lookup must be bounded and cancellation-aware.
Assert-Match $chzzkVod 'Client::builder\(\)' 'CHZZK video-detail API client must use an explicit builder.'
Assert-Match $chzzkVod 'connect_timeout\(CHZZK_API_CONNECT_TIMEOUT\)' 'CHZZK video-detail API connect timeout is missing.'
Assert-Match $chzzkVod '\.timeout\(CHZZK_API_TOTAL_TIMEOUT\)' 'CHZZK video-detail API total timeout is missing.'
Assert-Match $chzzkVod 'tokio::select!' 'CHZZK video-detail API lookup is not cancellation-raced.'
Assert-Match $chzzkVod 'wait_for_cancel\(cancel\)' 'CHZZK video-detail API cancellation waiter is missing.'
Assert-Match $chzzkVod 'chzzk_api_timeouts_are_bounded' 'CHZZK API timeout regression test is missing.'
Assert-Match $chzzkVod 'cancellation_waiter_observes_atomic_flag' 'CHZZK API cancellation regression test is missing.'

# Common VOD model contract: CHZZK is one logical part and still uses queue/history status.
Assert-Match $chzzkVod 'part_count:\s*1' 'CHZZK VOD analysis must expose one logical part.'
Assert-Match $chzzkVod 'current\.platform = PlatformId::Chzzk' 'CHZZK VOD runtime status does not preserve platform identity.'
Assert-Match $chzzkVod 'recognizes_only_chzzk_video_urls' 'CHZZK VOD URL regression test is missing.'
Assert-Match $chzzkVod 'validates_single_part_download_contract' 'CHZZK queue request regression test is missing.'
Assert-Match $chzzkVod 'stale_chzzk_job_dirs_are_scavenged_only' 'CHZZK stale-job cleanup regression test is missing.'
Assert-Match $chzzkVod 'cleanup_is_scoped_to_unique_job_directory' 'CHZZK owned-temp cleanup regression test is missing.'
Assert-Match $chzzkVod 'streamlink_staging_name_is_short_and_title_independent' 'CHZZK Windows long-path regression test is missing.'

Write-Host 'Storage ownership and CHZZK VOD contracts passed.'
