//! A hidden top-level window receives TaskbarCreated broadcasts. Message-only
//! windows do not. Wndproc only forwards presentation events, never core commands.
use crate::{
    AppState, MainWindow, QueueHistoryState,
    notifications::{NoticeQueue, Summary},
};
use slint::{ComponentHandle, Timer, TimerMode};
use std::{
    cell::{Cell, RefCell},
    rc::Rc,
    sync::mpsc,
    time::{Duration, Instant},
};
use windows::{
    Win32::{
        Foundation::{HWND, LPARAM, LRESULT, POINT, WPARAM},
        System::LibraryLoader::GetModuleHandleW,
        UI::{
            Shell::{
                NIF_ICON, NIF_INFO, NIF_MESSAGE, NIF_TIP, NIIF_INFO, NIIF_RESPECT_QUIET_TIME,
                NIIF_WARNING, NIM_ADD, NIM_DELETE, NIM_MODIFY, NIN_BALLOONHIDE, NIN_BALLOONTIMEOUT,
                NIN_BALLOONUSERCLICK, NOTIFYICONDATAW, Shell_NotifyIconW,
            },
            WindowsAndMessaging::*,
        },
    },
    core::{HSTRING, PCWSTR, w},
};

const CALLBACK: u32 = WM_APP + 24;
const OPEN: usize = 1;
const EXIT: usize = 2;
#[derive(Clone, Copy)]
enum Event {
    Open,
    Exit,
    ShellRestart,
    History,
    NoticeClosed,
}

struct State {
    hwnd: HWND,
    icon: HICON,
    taskbar_created: u32,
    events: mpsc::Sender<Event>,
    status: RefCell<String>,
    notices: RefCell<NoticeQueue>,
    notice_visible: Cell<bool>,
}

impl State {
    fn data(&self, tooltip: &str) -> NOTIFYICONDATAW {
        let mut data = NOTIFYICONDATAW {
            cbSize: std::mem::size_of::<NOTIFYICONDATAW>() as u32,
            hWnd: self.hwnd,
            uID: 1,
            uFlags: NIF_ICON | NIF_MESSAGE | NIF_TIP,
            uCallbackMessage: CALLBACK,
            hIcon: self.icon,
            ..Default::default()
        };
        for (dest, src) in data.szTip.iter_mut().take(127).zip(tooltip.encode_utf16()) {
            *dest = src;
        }
        data
    }

    fn show_notice(&self, summary: Summary) -> bool {
        let mut data = self.data("");
        data.uFlags = NIF_INFO;
        data.dwInfoFlags = (if summary.failed > 0 {
            NIIF_WARNING
        } else {
            NIIF_INFO
        }) | NIIF_RESPECT_QUIET_TIME;
        let title = if summary.failed > 0 {
            "Stream Archive 다운로드 결과"
        } else {
            "Stream Archive 다운로드 완료"
        };
        let body = format!(
            "SOOP / CHZZK VOD 완료 {}건 · 실패 {}건\n클릭하면 History에서 결과를 확인합니다.",
            summary.completed, summary.failed
        );
        for (dest, src) in data
            .szInfoTitle
            .iter_mut()
            .take(63)
            .zip(title.encode_utf16())
        {
            *dest = src;
        }
        for (dest, src) in data.szInfo.iter_mut().take(255).zip(body.encode_utf16()) {
            *dest = src;
        }
        let shown = unsafe { Shell_NotifyIconW(NIM_MODIFY, &data).as_bool() };
        self.notice_visible.set(shown);
        shown
    }

    fn clear_notice(&self) {
        self.notices.borrow_mut().clear();
        if self.notice_visible.replace(false) {
            let mut data = self.data("");
            data.uFlags = NIF_INFO;
            let _ = unsafe { Shell_NotifyIconW(NIM_MODIFY, &data) };
        }
    }

    fn ensure(&self, tooltip: &str) -> bool {
        let data = self.data(tooltip);
        // Verify the icon still exists, or re-add it after Explorer restarts.
        unsafe {
            Shell_NotifyIconW(NIM_MODIFY, &data).as_bool()
                || Shell_NotifyIconW(NIM_ADD, &data).as_bool()
        }
    }
}

struct Tray {
    state: Box<State>,
}
impl Tray {
    fn new(events: mpsc::Sender<Event>) -> Result<Self, String> {
        // Native resources and callbacks stay on the Slint UI thread.
        unsafe {
            let module = GetModuleHandleW(None).map_err(|e| e.to_string())?;
            let class = w!("StreamArchiveTrayWindow");
            let wc = WNDCLASSW {
                lpfnWndProc: Some(wndproc),
                hInstance: module.into(),
                lpszClassName: class,
                ..Default::default()
            };
            // An existing class is harmless; CreateWindowExW reports real errors.
            let _ = RegisterClassW(&wc);
            let hwnd = CreateWindowExW(
                WS_EX_TOOLWINDOW,
                class,
                w!("Stream Archive tray"),
                WINDOW_STYLE(0),
                0,
                0,
                0,
                0,
                None,
                None,
                Some(module.into()),
                None,
            )
            .map_err(|e| e.to_string())?;
            // Resource 1 is the existing multi-frame icon generated by build.rs.
            let icon = match LoadImageW(
                Some(module.into()),
                PCWSTR(std::ptr::without_provenance(1)),
                IMAGE_ICON,
                32,
                32,
                IMAGE_FLAGS(0),
            ) {
                Ok(handle) => HICON(handle.0),
                Err(error) => {
                    let _ = DestroyWindow(hwnd);
                    return Err(error.to_string());
                }
            };
            let taskbar_created = RegisterWindowMessageW(w!("TaskbarCreated"));
            if taskbar_created == 0 {
                let _ = DestroyIcon(icon);
                let _ = DestroyWindow(hwnd);
                return Err("TaskbarCreated message registration failed".into());
            }
            let state = Box::new(State {
                hwnd,
                icon,
                taskbar_created,
                status: RefCell::new("상태 확인 중".into()),
                notices: RefCell::new(NoticeQueue::default()),
                notice_visible: Cell::new(false),
                events,
            });
            SetWindowLongPtrW(hwnd, GWLP_USERDATA, state.as_ref() as *const State as isize);
            let tray = Self { state };
            if !tray.state.ensure("Stream Archive") {
                return Err("Windows 트레이 아이콘 등록 실패".into());
            }
            Ok(tray)
        }
    }
}
impl Drop for Tray {
    fn drop(&mut self) {
        unsafe {
            let _ = Shell_NotifyIconW(NIM_DELETE, &self.state.data(""));
            SetWindowLongPtrW(self.state.hwnd, GWLP_USERDATA, 0);
            let _ = DestroyWindow(self.state.hwnd);
            let _ = DestroyIcon(self.state.icon);
        }
    }
}

unsafe extern "system" fn wndproc(
    hwnd: HWND,
    message: u32,
    wparam: WPARAM,
    lparam: LPARAM,
) -> LRESULT {
    let ptr = unsafe { GetWindowLongPtrW(hwnd, GWLP_USERDATA) } as *const State;
    if !ptr.is_null() {
        // Box is stable until Drop clears USERDATA before destroying HWND.
        let state = unsafe { &*ptr };
        if message == state.taskbar_created {
            let _ = state.events.send(Event::ShellRestart);
            return LRESULT(0);
        }
        if message == CALLBACK {
            match lparam.0 as u32 {
                NIN_BALLOONUSERCLICK => {
                    let _ = state.events.send(Event::History);
                    let _ = state.events.send(Event::NoticeClosed);
                }
                NIN_BALLOONHIDE | NIN_BALLOONTIMEOUT => {
                    let _ = state.events.send(Event::NoticeClosed);
                }
                WM_LBUTTONUP => {
                    let _ = state.events.send(Event::Open);
                }
                WM_RBUTTONUP | WM_CONTEXTMENU => unsafe {
                    popup(state);
                },
                _ => {}
            }
            return LRESULT(0);
        }
    }
    unsafe { DefWindowProcW(hwnd, message, wparam, lparam) }
}

unsafe fn popup(state: &State) {
    unsafe {
        let Ok(menu) = CreatePopupMenu() else { return };
        let _ = AppendMenuW(menu, MF_STRING, OPEN, w!("Stream Archive 열기"));
        let label = HSTRING::from(state.status.borrow().as_str());
        let _ = AppendMenuW(menu, MF_STRING | MF_GRAYED, 3, &label);
        let _ = AppendMenuW(menu, MF_SEPARATOR, 0, PCWSTR::null());
        let _ = AppendMenuW(menu, MF_STRING, EXIT, w!("종료"));
        let mut point = POINT::default();
        if GetCursorPos(&mut point).is_ok() {
            let _ = SetForegroundWindow(state.hwnd);
            let command = TrackPopupMenu(
                menu,
                TPM_RETURNCMD | TPM_RIGHTBUTTON,
                point.x,
                point.y,
                None,
                state.hwnd,
                None,
            )
            .0 as usize;
            let _ = PostMessageW(Some(state.hwnd), WM_NULL, WPARAM(0), LPARAM(0));
            match command {
                OPEN => {
                    let _ = state.events.send(Event::Open);
                }
                EXIT => {
                    let _ = state.events.send(Event::Exit);
                }
                _ => {}
            }
        }
        let _ = DestroyMenu(menu);
    }
}

pub struct Desktop {
    _timer: Timer,
    _tray: Rc<Option<Tray>>,
}

fn restore(ui: &MainWindow) {
    ui.window().set_minimized(false);
    if let Err(error) = ui.show() {
        eprintln!("창 복원 실패: {error}");
    }
    use slint::winit_030::WinitWindowAccessor;
    ui.window()
        .with_winit_window(|window| window.focus_window());
}

pub fn bind(ui: &MainWindow) -> Desktop {
    let (events, receiver) = mpsc::channel();
    let tray = Rc::new(match Tray::new(events) {
        Ok(tray) => Some(tray),
        Err(error) => {
            ui.global::<AppState>()
                .set_desktop_status(format!("트레이 사용 불가: {error}").into());
            None
        }
    });
    let clear_tray = tray.clone();
    ui.global::<AppState>().on_clear_download_notices(move || {
        if let Some(tray) = clear_tray.as_ref().as_ref() {
            tray.state.clear_notice();
        }
    });
    let weak = ui.as_weak();
    let notice_tray = tray.clone();
    ui.global::<AppState>()
        .on_download_notice(move |completed, failed| {
            let Some(ui) = weak.upgrade() else { return };
            let state = ui.global::<AppState>();
            if !state.get_download_notifications_enabled() || state.get_desktop_exit_pending() {
                return;
            }
            if let Some(tray) = notice_tray.as_ref().as_ref() {
                tray.state
                    .notices
                    .borrow_mut()
                    .add(Summary { completed, failed }, Instant::now());
            } else {
                state.set_download_notifications_status(
                    "트레이 등록 실패로 알림을 표시하지 못했습니다. History에서 결과를 확인하세요."
                        .into(),
                );
            }
        });
    let weak = ui.as_weak();
    let close_tray = tray.clone();
    let informed = Cell::new(false);
    ui.window().on_close_requested(move || {
        let Some(ui) = weak.upgrade() else {
            return slint::CloseRequestResponse::KeepWindowShown;
        };
        let state = ui.global::<AppState>();
        if state.get_desktop_exit_pending()
            || (!state.get_settings_loaded() && state.get_settings_busy())
        {
            return slint::CloseRequestResponse::KeepWindowShown;
        }
        if state.get_close_to_tray() {
            if let Some(tray) = close_tray.as_ref().as_ref()
                && tray.state.ensure(&format!("Stream Archive — {}", state.get_desktop_status()))
            {
                if !informed.replace(true) {
                    super::notify(&ui, "창을 닫아도 녹화·다운로드·채널 감시가 계속 실행됩니다.\n앱을 종료하려면 트레이 메뉴의 ‘종료’를 선택하세요.");
                }
                // The shell may have restarted while the information dialog was open.
                if tray.state.ensure(&format!("Stream Archive — {}", state.get_desktop_status())) {
                    return slint::CloseRequestResponse::HideWindow;
                }
            }
            super::notify(&ui, "트레이 아이콘을 등록하지 못해 창을 유지합니다.\n종료하려면 설정에서 ‘프로그램 종료’를 선택해 저장하세요.");
        } else {
            state.invoke_desktop_exit();
        }
        slint::CloseRequestResponse::KeepWindowShown
    });
    let weak = ui.as_weak();
    let timer_tray = tray.clone();
    let timer = Timer::default();
    let mut last_poll = Instant::now();
    timer.start(TimerMode::Repeated, Duration::from_millis(100), move || {
        let Some(ui) = weak.upgrade() else { return };
        let state = ui.global::<AppState>();
        let mut recover = false;
        while let Ok(event) = receiver.try_recv() {
            match event {
                Event::Open => restore(&ui),
                Event::Exit => {
                    restore(&ui);
                    state.invoke_desktop_exit();
                }
                Event::ShellRestart => {
                    recover = true;
                    if let Some(tray) = timer_tray.as_ref().as_ref() {
                        tray.state.notice_visible.set(false);
                        tray.state.notices.borrow_mut().closed();
                    }
                }
                Event::NoticeClosed => {
                    if let Some(tray) = timer_tray.as_ref().as_ref() {
                        tray.state.notice_visible.set(false);
                        tray.state.notices.borrow_mut().closed();
                    }
                }
                Event::History => {
                    restore(&ui);
                    state.set_active_page("History".into());
                    let history = ui.global::<QueueHistoryState>();
                    history.set_history_view("VOD".into());
                    history.set_history_search("".into());
                    history.set_history_status("".into());
                    history.set_history_from_date("".into());
                    history.set_history_to_date("".into());
                    history.set_history_limit("100".into());
                    history.invoke_history_refresh();
                }
            }
        }
        if let Some(tray) = timer_tray.as_ref().as_ref() {
            if !state.get_download_notifications_enabled() || state.get_desktop_exit_pending() {
                tray.state.clear_notice();
            } else {
                let summary = tray.state.notices.borrow_mut().take(Instant::now());
                if let Some(summary) = summary {
                    // Best effort only; never block downloads or show a modal error.
                    if !tray
                        .state
                        .ensure(&format!("Stream Archive — {}", state.get_desktop_status()))
                        || !tray.state.show_notice(summary)
                    {
                        tray.state.notices.borrow_mut().closed();
                        state.set_download_notifications_status(
                            "Windows 알림 전송 실패. History에서 결과를 확인하세요.".into(),
                        );
                    } else {
                        state.set_download_notifications_status("".into());
                    }
                }
            }
        }
        if recover || last_poll.elapsed() >= Duration::from_secs(2) {
            last_poll = Instant::now();
            if !state.get_desktop_exit_pending() {
                state.invoke_desktop_poll();
            }
            if let Some(tray) = timer_tray.as_ref().as_ref() {
                *tray.state.status.borrow_mut() = state.get_desktop_status().to_string();
                if !tray
                    .state
                    .ensure(&format!("Stream Archive — {}", state.get_desktop_status()))
                    && !ui.window().is_visible()
                {
                    restore(&ui);
                    super::notify(
                        &ui,
                        "Windows 트레이를 복구하지 못해 창을 다시 표시했습니다.",
                    );
                }
            }
        }
    });
    Desktop {
        _timer: timer,
        _tray: tray,
    }
}
