//! A hidden top-level window receives TaskbarCreated broadcasts. Message-only
//! windows do not. Wndproc only forwards presentation events, never core commands.
use crate::{AppState, MainWindow};
use slint::{ComponentHandle, Timer, TimerMode};
use std::{
    cell::{Cell, RefCell},
    rc::Rc,
    sync::mpsc,
    time::{Duration, Instant},
};
use windows::{
    Win32::{
        Foundation::{HWND, LPARAM, LRESULT, POINT, WPARAM},
        System::LibraryLoader::GetModuleHandleW,
        UI::{
            Shell::{
                NIF_ICON, NIF_MESSAGE, NIF_TIP, NIM_ADD, NIM_DELETE, NIM_MODIFY,
                NOTIFYICONDATAW, Shell_NotifyIconW,
            },
            WindowsAndMessaging::*,
        },
    },
    core::{HSTRING, PCWSTR, w},
};

const CALLBACK: u32 = WM_APP + 24;
const OPEN: usize = 1;
const EXIT: usize = 2;
#[derive(Clone, Copy)]
enum Event {
    Open,
    Exit,
    ShellRestart,
}

struct State {
    hwnd: HWND,
    icon: HICON,
    taskbar_created: u32,
    events: mpsc::Sender<Event>,
    status: RefCell<String>,
}

impl State {
    fn data(&self, tooltip: &str) -> NOTIFYICONDATAW {
        let mut data = NOTIFYICONDATAW {
            cbSize: std::mem::size_of::<NOTIFYICONDATAW>() as u32,
            hWnd: self.hwnd,
            uID: 1,
            uFlags: NIF_ICON | NIF_MESSAGE | NIF_TIP,
            uCallbackMessage: CALLBACK,
            hIcon: self.icon,
            ..Default::default()
        };
        for (dest, src) in data.szTip.iter_mut().take(127).zip(tooltip.encode_utf16()) {
            *dest = src;
        }
        data
    }

    fn ensure(&self, tooltip: &str) -> bool {
        let data = self.data(tooltip);
        // Verify the icon still exists, or re-add it after Explorer restarts.
        unsafe {
            Shell_NotifyIconW(NIM_MODIFY, &data).as_bool()
                || Shell_NotifyIconW(NIM_ADD, &data).as_bool()
        }
    }
}

struct Tray {
    state: Box<State>,
}
impl Tray {
    fn new(events: mpsc::Sender<Event>) -> Result<Self, String> {
        // Native resources and callbacks stay on the Slint UI thread.
        unsafe {
            let module = GetModuleHandleW(None).map_err(|e| e.to_string())?;
            let class = w!("StreamArchiveTrayWindow");
            let wc = WNDCLASSW {
                lpfnWndProc: Some(wndproc),
                hInstance: module.into(),
                lpszClassName: class,
                ..Default::default()
            };
            // An existing class is harmless; CreateWindowExW reports real errors.
            let _ = RegisterClassW(&wc);
            let hwnd = CreateWindowExW(
                WS_EX_TOOLWINDOW,
                class,
                w!("Stream Archive tray"),
                WINDOW_STYLE(0),
                0,
                0,
                0,
                0,
                None,
                None,
                Some(module.into()),
                None,
            ).map_err(|e| e.to_string())?;
            // Resource 1 is the existing multi-frame icon generated by build.rs.
            let icon = match LoadImageW(
                Some(module.into()),
                PCWSTR(1usize as *const u16),
                IMAGE_ICON,
                32,
                32,
                IMAGE_FLAGS(0),
            ) {
                Ok(handle) => HICON(handle.0),
                Err(error) => {
                    let _ = DestroyWindow(hwnd);
                    return Err(error.to_string());
                }
            };
            let taskbar_created = RegisterWindowMessageW(w!("TaskbarCreated"));
            if taskbar_created == 0 {
                let _ = DestroyIcon(icon);
                let _ = DestroyWindow(hwnd);
                return Err("TaskbarCreated message registration failed".into());
            }
            let state = Box::new(State {
                hwnd,
                icon,
                taskbar_created,
                status: RefCell::new("상태 확인 중".into()),
                events,
            });
            SetWindowLongPtrW(hwnd, GWLP_USERDATA, state.as_ref() as *const State as isize);
            let tray = Self { state };
            if !tray.state.ensure("Stream Archive") {
                return Err("Windows 트레이 아이콘 등록 실패".into());
            }
            Ok(tray)
        }
    }
}
impl Drop for Tray {
    fn drop(&mut self) {
        unsafe {
            let _ = Shell_NotifyIconW(NIM_DELETE, &self.state.data(""));
            SetWindowLongPtrW(self.state.hwnd, GWLP_USERDATA, 0);
            let _ = DestroyWindow(self.state.hwnd);
            let _ = DestroyIcon(self.state.icon);
        }
    }
}

unsafe extern "system" fn wndproc(
    hwnd: HWND,
    message: u32,
    wparam: WPARAM,
    lparam: LPARAM,
) -> LRESULT {
    let ptr = unsafe { GetWindowLongPtrW(hwnd, GWLP_USERDATA) } as *const State;
    if !ptr.is_null() {
        // Box is stable until Drop clears USERDATA before destroying HWND.
        let state = unsafe { &*ptr };
        if message == state.taskbar_created {
            let _ = state.events.send(Event::ShellRestart);
            return LRESULT(0);
        }
        if message == CALLBACK {
            match lparam.0 as u32 {
                WM_LBUTTONUP => { let _ = state.events.send(Event::Open); }
                WM_RBUTTONUP | WM_CONTEXTMENU => unsafe { popup(state); },
                _ => {}
            }
            return LRESULT(0);
        }
    }
    unsafe { DefWindowProcW(hwnd, message, wparam, lparam) }
}

unsafe fn popup(state: &State) {
    unsafe {
        let Ok(menu) = CreatePopupMenu() else { return };
        let _ = AppendMenuW(menu, MF_STRING, OPEN, w!("Stream Archive 열기"));
        let label = HSTRING::from(state.status.borrow().as_str());
        let _ = AppendMenuW(menu, MF_STRING | MF_GRAYED, 3, &label);
        let _ = AppendMenuW(menu, MF_SEPARATOR, 0, PCWSTR::null());
        let _ = AppendMenuW(menu, MF_STRING, EXIT, w!("종료"));
        let mut point = POINT::default();
        if GetCursorPos(&mut point).is_ok() {
            let _ = SetForegroundWindow(state.hwnd);
            let command = TrackPopupMenu(
                menu, TPM_RETURNCMD | TPM_RIGHTBUTTON, point.x, point.y,
                None, state.hwnd, None,
            ).0 as usize;
            let _ = PostMessageW(Some(state.hwnd), WM_NULL, WPARAM(0), LPARAM(0));
            match command {
                OPEN => { let _ = state.events.send(Event::Open); }
                EXIT => { let _ = state.events.send(Event::Exit); }
                _ => {}
            }
        }
        let _ = DestroyMenu(menu);
    }
}

pub struct Desktop {
    _timer: Timer,
    _tray: Rc<Option<Tray>>,
}

fn restore(ui: &MainWindow) {
    ui.window().set_minimized(false);
    if let Err(error) = ui.show() {
        eprintln!("창 복원 실패: {error}");
    }
    use slint::winit_030::WinitWindowAccessor;
    ui.window().with_winit_window(|window| window.focus_window());
}

pub fn bind(ui: &MainWindow) -> Desktop {
    let (events, receiver) = mpsc::channel();
    let tray = Rc::new(match Tray::new(events) {
        Ok(tray) => Some(tray),
        Err(error) => {
            ui.global::<AppState>().set_desktop_status(format!("트레이 사용 불가: {error}").into());
            None
        }
    });
    let weak = ui.as_weak();
    let close_tray = tray.clone();
    let informed = Cell::new(false);
    ui.window().on_close_requested(move || {
        let Some(ui) = weak.upgrade() else {
            return slint::CloseRequestResponse::KeepWindowShown;
        };
        let state = ui.global::<AppState>();
        if state.get_desktop_exit_pending() {
            return slint::CloseRequestResponse::KeepWindowShown;
        }
        if state.get_close_to_tray() {
            if let Some(tray) = close_tray.as_ref().as_ref() {
                if tray.state.ensure(&format!("Stream Archive — {}", state.get_desktop_status())) {
                    if !informed.replace(true) {
                        super::notify(&ui, "창을 닫아도 녹화·다운로드·채널 감시가 계속 실행됩니다.\n앱을 종료하려면 트레이 메뉴의 ‘종료’를 선택하세요.");
                    }
                    // The shell may have restarted while the information dialog was open.
                    if tray.state.ensure(&format!("Stream Archive — {}", state.get_desktop_status())) {
                        return slint::CloseRequestResponse::HideWindow;
                    }
                }
            }
            super::notify(&ui, "트레이 아이콘을 등록하지 못해 창을 유지합니다.\n종료하려면 설정에서 ‘프로그램 종료’를 선택해 저장하세요.");
        } else {
            state.invoke_desktop_exit();
        }
        slint::CloseRequestResponse::KeepWindowShown
    });
    let weak = ui.as_weak();
    let timer_tray = tray.clone();
    let timer = Timer::default();
    let mut last_poll = Instant::now();
    timer.start(TimerMode::Repeated, Duration::from_millis(100), move || {
        let Some(ui) = weak.upgrade() else { return };
        let state = ui.global::<AppState>();
        let mut recover = false;
        while let Ok(event) = receiver.try_recv() {
            match event {
                Event::Open => restore(&ui),
                Event::Exit => { restore(&ui); state.invoke_desktop_exit(); }
                Event::ShellRestart => recover = true,
            }
        }
        if recover || last_poll.elapsed() >= Duration::from_secs(2) {
            last_poll = Instant::now();
            if !state.get_desktop_exit_pending() { state.invoke_desktop_poll(); }
            if let Some(tray) = timer_tray.as_ref().as_ref() {
                *tray.state.status.borrow_mut() = state.get_desktop_status().to_string();
                if !tray.state.ensure(&format!("Stream Archive — {}", state.get_desktop_status()))
                    && !ui.window().is_visible()
                {
                    restore(&ui);
                    super::notify(&ui, "Windows 트레이를 복구하지 못해 창을 다시 표시했습니다.");
                }
            }
        }
    });
    Desktop { _timer: timer, _tray: tray }
}
