use crate::{
    backend::LogBuffer,
    model::{VodAnalysisView, VodAnalyzeRequest, VodDownloadRequest, VodJobStatus, VodPartInfo, VodQualityOption},
    security::unprotect_secret,
};
use anyhow::{anyhow, bail, Context, Result};
use chrono::Utc;
use regex::Regex;
use reqwest::{header::{COOKIE, REFERER, SET_COOKIE}, Client, Response};
use serde_json::Value;
use std::{
    collections::{BTreeMap, HashMap},
    fs,
    path::{Path, PathBuf},
    process::Stdio,
    sync::{atomic::{AtomicBool, Ordering}, Arc},
    time::Duration,
};
use tokio::{
    io::{AsyncBufReadExt, BufReader},
    process::{Child, Command},
    sync::{Mutex, RwLock},
    task::JoinHandle,
};
use url::Url;
use uuid::Uuid;

const USER_AGENT: &str = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/151 Safari/537.36";
const CF_NAMES: &[&str] = &["CloudFront-Key-Pair-Id", "CloudFront-Policy", "CloudFront-Signature"];
const LOGIN_COOKIE_NAMES: &[&str] = &["AuthTicket", "BbsTicket", "UserTicket", "RDB", "PdboxTicket"];

#[derive(Debug, Clone)]
struct Tools { yt_dlp: PathBuf, ffmpeg: Option<PathBuf> }

#[derive(Debug, Clone)]
struct VodMetadata {
    title: String,
    streamer: String,
    streamer_id: String,
    date: String,
    entries: Vec<VodEntry>,
}

#[derive(Debug, Clone)]
struct VodEntry { manifest_url: String, duration_seconds: u64 }

#[derive(Debug, Clone)]
struct NetscapeCookie {
    domain: String,
    include_subdomains: bool,
    path: String,
    secure: bool,
    expires: i64,
    name: String,
    value: String,
}

#[derive(Debug, Clone, Default)]
struct CookieJar { items: Vec<NetscapeCookie> }

impl CookieJar {
    fn parse_file(path: &Path) -> Result<Self> {
        let text = fs::read_to_string(path).with_context(|| format!("Cookie 파일 읽기 실패: {}", path.display()))?;
        let mut items = Vec::new();
        for raw in text.lines() {
            let line = raw.trim_end();
            if line.trim().is_empty() || (line.starts_with('#') && !line.starts_with("#HttpOnly_")) { continue; }
            let normalized = line.strip_prefix("#HttpOnly_").unwrap_or(line);
            let fields: Vec<&str> = normalized.splitn(7, '\t').collect();
            if fields.len() != 7 { continue; }
            items.push(NetscapeCookie {
                domain: fields[0].to_string(), include_subdomains: fields[1].eq_ignore_ascii_case("TRUE"),
                path: fields[2].to_string(), secure: fields[3].eq_ignore_ascii_case("TRUE"),
                expires: fields[4].parse().unwrap_or(0), name: fields[5].to_string(), value: fields[6].to_string(),
            });
        }
        if items.is_empty() { bail!("Cookie 파일이 Netscape 형식이 아니거나 비어 있습니다."); }
        Ok(Self { items })
    }

    fn write_file(&self, path: &Path) -> Result<()> {
        let mut out = String::from("# Netscape HTTP Cookie File\n# Generated by SOOP Rust VOD; do not share.\n");
        for c in &self.items {
            out.push_str(&format!("{}\t{}\t{}\t{}\t{}\t{}\t{}\n",
                c.domain, if c.include_subdomains {"TRUE"} else {"FALSE"}, c.path,
                if c.secure {"TRUE"} else {"FALSE"}, c.expires, sanitize_cookie_field(&c.name), sanitize_cookie_field(&c.value)));
        }
        fs::write(path, out).with_context(|| format!("Cookie 파일 저장 실패: {}", path.display()))
    }

    fn header_for(&self, url: &str) -> Result<String> {
        let url = Url::parse(url)?;
        let host = url.host_str().unwrap_or("").to_ascii_lowercase();
        let path = url.path();
        let now = Utc::now().timestamp();
        let values = self.items.iter().filter(|c| {
            if c.expires > 0 && c.expires < now { return false; }
            if c.secure && url.scheme() != "https" { return false; }
            let domain = c.domain.trim_start_matches('.').to_ascii_lowercase();
            let domain_ok = if c.include_subdomains || c.domain.starts_with('.') { host == domain || host.ends_with(&format!(".{domain}")) } else { host == domain };
            domain_ok && path.starts_with(if c.path.is_empty() { "/" } else { &c.path })
        }).map(|c| format!("{}={}", c.name, c.value)).collect::<Vec<_>>();
        Ok(values.join("; "))
    }

    fn upsert(&mut self, cookie: NetscapeCookie) {
        self.items.retain(|c| !(c.name.eq_ignore_ascii_case(&cookie.name) && c.domain.eq_ignore_ascii_case(&cookie.domain) && c.path == cookie.path));
        self.items.push(cookie);
    }

    fn remove_cloudfront(&mut self) { self.items.retain(|c| !c.name.to_ascii_lowercase().starts_with("cloudfront-")); }
    fn has_cloudfront(&self) -> bool { CF_NAMES.iter().all(|name| self.items.iter().any(|c| c.name.eq_ignore_ascii_case(name) && !c.value.is_empty())) }
    fn has_login(&self) -> bool { LOGIN_COOKIE_NAMES.iter().any(|name| self.items.iter().any(|c| c.name.eq_ignore_ascii_case(name) && !c.value.is_empty())) }

    fn cloudfront_header(&self) -> Result<String> {
        let mut map = HashMap::new();
        for c in &self.items { if CF_NAMES.iter().any(|n| c.name.eq_ignore_ascii_case(n)) { map.insert(c.name.to_ascii_lowercase(), c.value.clone()); } }
        let mut parts = Vec::new();
        for name in CF_NAMES {
            let value = map.get(&name.to_ascii_lowercase()).ok_or_else(|| anyhow!("{name} Cookie가 없습니다."))?;
            parts.push(format!("{name}={value}"));
        }
        Ok(parts.join("; "))
    }

    fn repair_cloudfront_scope(&mut self, manifest_url: &str) -> Result<()> {
        let host = Url::parse(manifest_url)?.host_str().ok_or_else(|| anyhow!("manifest host 없음"))?.to_ascii_lowercase();
        let mut latest: HashMap<String, NetscapeCookie> = HashMap::new();
        let mut keep = Vec::new();
        for c in self.items.drain(..) {
            if c.name.to_ascii_lowercase().starts_with("cloudfront-") { latest.insert(c.name.to_ascii_lowercase(), c); } else { keep.push(c); }
        }
        for name in CF_NAMES {
            let mut c = latest.remove(&name.to_ascii_lowercase()).ok_or_else(|| anyhow!("private_auth 응답에 {name} Cookie가 없습니다."))?;
            c.domain = host.clone(); c.include_subdomains = false; c.path = "/".into(); c.secure = true;
            keep.push(c);
        }
        self.items = keep;
        Ok(())
    }
}

struct JobRuntime { task: Option<JoinHandle<()>>, cancel: Arc<AtomicBool> }

pub struct VodManager {
    backend_dir: PathBuf,
    logs: LogBuffer,
    runtime: Mutex<JobRuntime>,
    status: Arc<RwLock<VodJobStatus>>,
}

impl VodManager {
    pub fn new(backend_dir: PathBuf, logs: LogBuffer) -> Self {
        Self { backend_dir, logs, runtime: Mutex::new(JobRuntime { task: None, cancel: Arc::new(AtomicBool::new(false)) }), status: Arc::new(RwLock::new(VodJobStatus::default())) }
    }

    pub async fn status(&self) -> VodJobStatus {
        let finished = { self.runtime.lock().await.task.as_ref().is_some_and(|t| t.is_finished()) };
        if finished { self.runtime.lock().await.task.take(); }
        self.status.read().await.clone()
    }

    pub async fn analyze(&self, req: VodAnalyzeRequest) -> Result<VodJobStatus> {
        self.start_job(VodJobKind::Analyze(req)).await
    }

    pub async fn download(&self, req: VodDownloadRequest) -> Result<VodJobStatus> {
        self.start_job(VodJobKind::Download(req)).await
    }

    async fn start_job(&self, kind: VodJobKind) -> Result<VodJobStatus> {
        let mut runtime = self.runtime.lock().await;
        if runtime.task.as_ref().is_some_and(|t| !t.is_finished()) { bail!("다른 VOD 작업이 이미 실행 중입니다."); }
        runtime.task.take();
        let cancel = Arc::new(AtomicBool::new(false));
        runtime.cancel = cancel.clone();
        let backend = self.backend_dir.clone();
        let logs = self.logs.clone();
        let status = self.status.clone();
        let job_id = Uuid::new_v4().to_string();
        {
            let mut s = status.write().await;
            *s = VodJobStatus { state: "STARTING".into(), running: true, job_id: Some(job_id.clone()), message: "VOD 작업 준비 중…".into(), started_at: Some(Utc::now().to_rfc3339()), ..Default::default() };
        }
        let task = tokio::spawn(async move {
            let result = match kind {
                VodJobKind::Analyze(req) => run_analysis(&backend, req, &logs, &status, &cancel).await.map(|_| ()),
                VodJobKind::Download(req) => run_download(&backend, req, &logs, &status, &cancel).await,
            };
            let mut s = status.write().await;
            s.running = false;
            s.finished_at = Some(Utc::now().to_rfc3339());
            if cancel.load(Ordering::SeqCst) {
                s.state = "CANCELLED".into(); s.message = "VOD 작업이 취소되었습니다.".into();
                logs.push("[VOD] job cancelled").await;
            } else if let Err(err) = result {
                s.state = "FAILED".into(); s.message = redact(&format!("{err:#}"));
                logs.push(format!("[VOD:ERR] {}", s.message)).await;
            }
        });
        runtime.task = Some(task);
        Ok(self.status.read().await.clone())
    }

    pub async fn cancel(&self) -> Result<VodJobStatus> {
        let runtime = self.runtime.lock().await;
        if runtime.task.as_ref().is_some_and(|t| !t.is_finished()) { runtime.cancel.store(true, Ordering::SeqCst); }
        drop(runtime);
        let mut s = self.status.write().await;
        if s.running { s.state = "CANCELLING".into(); s.message = "외부 프로세스 종료 중…".into(); }
        Ok(s.clone())
    }
}

enum VodJobKind { Analyze(VodAnalyzeRequest), Download(VodDownloadRequest) }

async fn run_analysis(backend: &Path, req: VodAnalyzeRequest, logs: &LogBuffer, status: &Arc<RwLock<VodJobStatus>>, cancel: &AtomicBool) -> Result<VodAnalysisView> {
    validate_url(&req.vod_url)?;
    validate_retries(req.max_retries)?;
    set_status(status, "ANALYZING", "VOD 분석 중…").await;
    let tools = resolve_tools(backend, &req.yt_dlp_path, &req.ffmpeg_path)?;
    let job_dir = job_dir(backend)?;
    let mut jar = init_cookie(backend, &tools, &req.vod_url, &req.cookie_mode, &req.cookie_file, &req.browser_name, &job_dir, cancel, logs).await?;
    let cookie_file = job_dir.join("cookies.txt");
    jar.write_file(&cookie_file)?;
    let mut metadata = get_metadata(&tools, &req.vod_url, &cookie_file, cancel, logs).await?;
    complete_metadata_from_api(&req.vod_url, &mut metadata, &jar).await.ok();
    let first = metadata.entries.first().ok_or_else(|| anyhow!("VOD PART를 찾지 못했습니다."))?.manifest_url.clone();
    if first.is_empty() { bail!("첫 번째 PART manifest URL이 없습니다."); }
    if !jar.has_cloudfront() {
        refresh_authorization(&req.vod_url, &metadata.streamer_id, &first, &mut jar, 1, logs).await?;
    } else { jar.repair_cloudfront_scope(&first)?; }
    let qualities = probe_manifest(&req.vod_url, &first, &jar).await?;
    jar.write_file(&cookie_file)?;
    let view = analysis_view(&req.vod_url, &metadata, qualities);
    {
        let mut s = status.write().await;
        s.state = "READY".into(); s.running = false; s.message = "분석 완료 · PART와 화질을 선택하세요.".into(); s.part_count = view.part_count; s.analysis = Some(view.clone()); s.percent = 100.0; s.finished_at = Some(Utc::now().to_rfc3339());
    }
    logs.push(format!("[VOD] analysis ready title={} streamer={} parts={}", metadata.title, metadata.streamer, metadata.entries.len())).await;
    cleanup_job_dir(&job_dir);
    Ok(view)
}

async fn run_download(backend: &Path, req: VodDownloadRequest, logs: &LogBuffer, status: &Arc<RwLock<VodJobStatus>>, cancel: &AtomicBool) -> Result<()> {
    validate_url(&req.vod_url)?; validate_retries(req.max_retries)?;
    if !req.quality.is_empty() && !Regex::new(r"^best(?:\[height<=\d+\])?$").unwrap().is_match(&req.quality) { bail!("지원하지 않는 VOD 화질 선택입니다."); }
    let tools = resolve_tools(backend, &req.yt_dlp_path, &req.ffmpeg_path)?;
    let output_dir = PathBuf::from(&req.output_directory);
    if req.output_directory.trim().is_empty() { bail!("VOD 출력 폴더가 비어 있습니다."); }
    fs::create_dir_all(&output_dir)?;
    let job_dir = job_dir(backend)?;
    let mut jar = init_cookie(backend, &tools, &req.vod_url, &req.cookie_mode, &req.cookie_file, &req.browser_name, &job_dir, cancel, logs).await?;
    let cookie_file = job_dir.join("cookies.txt"); jar.write_file(&cookie_file)?;
    let mut metadata = get_metadata(&tools, &req.vod_url, &cookie_file, cancel, logs).await?;
    complete_metadata_from_api(&req.vod_url, &mut metadata, &jar).await.ok();
    let selected = resolve_parts(&req.parts, metadata.entries.len())?;
    {
        let mut s = status.write().await; s.state="DOWNLOADING".into(); s.part_count=metadata.entries.len(); s.message="VOD 다운로드 시작".into();
        s.analysis=Some(analysis_view(&req.vod_url, &metadata, vec![VodQualityOption{value:"best".into(),label:"최고 화질 (자동)".into()}]));
    }
    let mut files = Vec::new();
    for part in selected {
        if cancel.load(Ordering::SeqCst) { cleanup_job_dir(&job_dir); return Ok(()); }
        let mut last_error = String::new();
        let output = collision_path(&output_dir, &format!("{}_{}_{:02}", metadata.date, safe_name(&metadata.streamer), part), ".mp4")?;
        for attempt in 1..=req.max_retries {
            if cancel.load(Ordering::SeqCst) { cleanup_incomplete(&output); cleanup_job_dir(&job_dir); return Ok(()); }
            if attempt > 1 {
                jar = renew_base_cookie(backend, &tools, &req.vod_url, &req.cookie_mode, &req.cookie_file, &req.browser_name, &job_dir, cancel, logs).await?;
                jar.write_file(&cookie_file)?;
            }
            {
                let mut s=status.write().await; s.current_part=part; s.state="REFRESHING".into(); s.message=format!("PART {part} 최신 URL/인증 갱신 중 ({attempt}/{})", req.max_retries);
            }
            let mut refreshed = get_metadata(&tools, &req.vod_url, &cookie_file, cancel, logs).await?;
            complete_metadata_from_api(&req.vod_url, &mut refreshed, &jar).await.ok();
            let url = refreshed.entries.get(part-1).map(|e| e.manifest_url.clone()).filter(|s| !s.is_empty()).or_else(|| metadata.entries.get(part-1).map(|e| e.manifest_url.clone())).ok_or_else(|| anyhow!("PART {part} URL이 없습니다."))?;
            if !(attempt == 1 && jar.has_cloudfront()) {
                jar.remove_cloudfront();
                if let Err(err)=refresh_authorization(&req.vod_url, &refreshed.streamer_id, &url, &mut jar, attempt, logs).await { last_error=err.to_string(); sleep_retry(attempt, cancel).await; continue; }
            } else { jar.repair_cloudfront_scope(&url)?; }
            if let Err(err)=probe_manifest(&req.vod_url, &url, &jar).await { last_error=err.to_string(); sleep_retry(attempt, cancel).await; continue; }
            jar.write_file(&cookie_file)?;
            {
                let mut s=status.write().await; s.state="DOWNLOADING".into(); s.message=format!("PART {part}/{} 다운로드 중…", metadata.entries.len());
            }
            match download_part(&tools, &req, &cookie_file, &url, &output, part, metadata.entries.len(), status, cancel, logs).await {
                Ok(()) => { files.push(output.clone()); last_error.clear(); break; }
                Err(err) => { last_error=err.to_string(); cleanup_incomplete(&output); logs.push(format!("[VOD:WARN] PART {part} retry {attempt}/{}: {}", req.max_retries, redact(&last_error))).await; sleep_retry(attempt, cancel).await; }
            }
        }
        if !last_error.is_empty() && !output.is_file() { cleanup_job_dir(&job_dir); bail!("PART {part} 다운로드 실패: {last_error}"); }
    }
    if cancel.load(Ordering::SeqCst) { cleanup_job_dir(&job_dir); return Ok(()); }
    let final_file = if files.len() > 1 && req.merge { merge_parts(&tools, &metadata, &files, &output_dir, status, cancel, logs).await? } else { files.first().cloned().ok_or_else(|| anyhow!("다운로드된 PART가 없습니다."))? };
    {
        let mut s=status.write().await; s.state="COMPLETED".into(); s.running=false; s.message="VOD 다운로드가 완료되었습니다.".into(); s.output_file=Some(final_file.display().to_string()); s.percent=100.0; s.finished_at=Some(Utc::now().to_rfc3339());
    }
    logs.push(format!("[VOD] completed file={}", final_file.display())).await;
    cleanup_job_dir(&job_dir);
    Ok(())
}

async fn init_cookie(backend:&Path, tools:&Tools, vod_url:&str, mode:&str, cookie_file:&str, browser:&str, job_dir:&Path, cancel:&AtomicBool, logs:&LogBuffer)->Result<CookieJar>{
    match mode.to_ascii_uppercase().as_str() {
        "SOOP_LOGIN" => login_cookie(backend, vod_url, logs).await,
        "FILE" => CookieJar::parse_file(Path::new(cookie_file)),
        "BROWSER" => {
            let target=job_dir.join("browser-cookies.txt");
            run_simple_process(&tools.yt_dlp, &["--cookies-from-browser",browser,"--cookies",target.to_string_lossy().as_ref(),"--skip-download",vod_url], cancel, logs, "yt-dlp cookie").await?;
            CookieJar::parse_file(&target)
        }
        other => bail!("지원하지 않는 Cookie 모드입니다: {other}"),
    }
}

async fn renew_base_cookie(backend:&Path, tools:&Tools, vod_url:&str, mode:&str, cookie_file:&str, browser:&str, job_dir:&Path, cancel:&AtomicBool, logs:&LogBuffer)->Result<CookieJar>{
    init_cookie(backend, tools, vod_url, mode, cookie_file, browser, job_dir, cancel, logs).await
}

async fn login_cookie(backend:&Path, vod_url:&str, logs:&LogBuffer)->Result<CookieJar>{
    let settings=read_ini(&backend.join("SOOP_LIVE_SETTING.ini"))?;
    let username=settings.get("SOOP_USERNAME").cloned().unwrap_or_default();
    let password=unprotect_secret(settings.get("SOOP_PASSWORD").map(String::as_str).unwrap_or(""), "SOOP_PASSWORD")?;
    if username.is_empty()||password.is_empty(){bail!("SOOP 아이디와 비밀번호를 먼저 설정해 주세요.");}
    let client=http_client()?;
    let response=client.post("https://login.sooplive.com/app/LoginAction.php").header(REFERER,"https://www.sooplive.com/").form(&[("szWork","login"),("szType","json"),("szUid",username.as_str()),("szPassword",password.as_str()),("isSaveId","true"),("isSavePw","false"),("isSaveJoin","false"),("isLoginRetain","Y")]).send().await?;
    let mut jar=CookieJar::default(); collect_set_cookies(&mut jar,&response,"sooplive.com");
    let value:Value=response.error_for_status()?.json().await?;
    if value.get("RESULT").and_then(Value::as_i64)!=Some(1){bail!("SOOP 로그인 실패 RESULT={:?}",value.get("RESULT"));}
    let cookie=jar.header_for("https://afevent2.sooplive.com/")?;
    let verify=client.get("https://afevent2.sooplive.com/api/get_private_info.php").header(REFERER,"https://www.sooplive.com/").header(COOKIE,cookie).send().await?;
    collect_set_cookies(&mut jar,&verify,"sooplive.com");
    let auth:Value=verify.error_for_status()?.json().await?;
    if auth.pointer("/CHANNEL/LOGIN_ID").and_then(Value::as_str).unwrap_or("").is_empty(){bail!("SOOP 로그인 검증에 실패했습니다.");}
    let cookie=jar.header_for(vod_url)?;
    let mut req=client.get(vod_url).header(REFERER,"https://vod.sooplive.com/"); if !cookie.is_empty(){req=req.header(COOKIE,cookie);}
    let visit=req.send().await?; collect_set_cookies(&mut jar,&visit,"sooplive.com"); let _=visit.error_for_status()?;
    jar.remove_cloudfront();
    logs.push(format!("[VOD:AUTH] SOOP login session ready: {username}")).await;
    Ok(jar)
}

async fn refresh_authorization(vod_url:&str, streamer_id:&str, manifest_url:&str, jar:&mut CookieJar, attempt:u32, logs:&LogBuffer)->Result<()> {
    jar.remove_cloudfront();
    let title_no=title_no(vod_url)?;
    let client=http_client()?;
    let cookie=jar.header_for("https://live.sooplive.com/api/private_auth.php")?;
    let response=client.post("https://live.sooplive.com/api/private_auth.php").header(REFERER,vod_url).header("Origin","https://vod.sooplive.com").header("Accept","application/json, text/plain, */*").header(COOKIE,cookie).form(&[("type","vod"),("strm_id",streamer_id),("title_no",title_no.as_str()),("url",manifest_url)]).send().await?;
    collect_cloudfront_headers(jar,&response,manifest_url)?;
    let text=response.error_for_status()?.text().await?;
    let value:Value=serde_json::from_str(&text).unwrap_or(Value::Null);
    if value.get("result").and_then(Value::as_i64)!=Some(1){
        let code=value.pointer("/data/code").and_then(Value::as_i64).map(|v|v.to_string()).unwrap_or_default();
        let msg=value.pointer("/data/message").and_then(Value::as_str).unwrap_or("private_auth 실패");
        bail!("private_auth {code}: {msg}");
    }
    collect_cloudfront_json(jar,&value,manifest_url);
    jar.repair_cloudfront_scope(manifest_url)?;
    logs.push(format!("[VOD:AUTH] private_auth OK attempt={attempt} host={}",Url::parse(manifest_url)?.host_str().unwrap_or(""))).await;
    Ok(())
}

async fn probe_manifest(vod_url:&str,url:&str,jar:&CookieJar)->Result<Vec<VodQualityOption>>{
    let client=http_client()?; let cookie=jar.cloudfront_header()?;
    let response=client.get(url).header(REFERER,vod_url).header("Origin","https://vod.sooplive.com").header(COOKIE,cookie).send().await?;
    let status=response.status(); let text=response.text().await.unwrap_or_default();
    if !status.is_success(){bail!("manifest authorization check failed: HTTP {status}, host={}",Url::parse(url)?.host_str().unwrap_or(""));}
    let mut heights=Regex::new(r"RESOLUTION=\d+x(?P<h>\d+)").unwrap().captures_iter(&text).filter_map(|c|c.name("h")?.as_str().parse::<u32>().ok()).collect::<Vec<_>>();
    heights.sort_unstable_by(|a,b|b.cmp(a)); heights.dedup();
    let mut out=vec![VodQualityOption{value:"best".into(),label:"최고 화질 (자동)".into()}];
    for h in heights {out.push(VodQualityOption{value:format!("best[height<={h}]"),label:format!("{h}p")});}
    Ok(out)
}

async fn get_metadata(tools:&Tools,vod_url:&str,cookie_file:&Path,cancel:&AtomicBool,logs:&LogBuffer)->Result<VodMetadata>{
    let args=vec!["--cookies".to_string(),cookie_file.display().to_string(),"--flat-playlist".into(),"--ignore-no-formats-error".into(),"--dump-single-json".into(),"--no-warnings".into(),vod_url.into()];
    let output=run_capture(&tools.yt_dlp,&args,cancel,logs,"yt-dlp metadata").await?;
    let info:Value=serde_json::from_str(&output).context("VOD JSON 파싱 실패")?;
    let entries=info.get("entries").and_then(Value::as_array).ok_or_else(||anyhow!("VOD PART를 찾지 못했습니다."))?;
    if entries.is_empty(){bail!("VOD PART를 찾지 못했습니다.");}
    let streamer_id=str_field(&info,"uploader_id").or_else(||entries.first().and_then(|v|str_field(v,"uploader_id"))).ok_or_else(||anyhow!("VOD BJ ID를 찾지 못했습니다."))?;
    let streamer=str_field(&info,"uploader").or_else(||entries.first().and_then(|v|str_field(v,"uploader"))).unwrap_or_else(||streamer_id.clone());
    let title=str_field(&info,"title").or_else(||entries.first().and_then(|v|str_field(v,"title"))).unwrap_or_else(||"UNKNOWN".into());
    let raw_date=str_field(&info,"upload_date").or_else(||entries.first().and_then(|v|str_field(v,"upload_date"))).unwrap_or_else(||Utc::now().format("%Y%m%d").to_string());
    let date=if raw_date.len()==8{raw_date[2..].to_string()}else{Utc::now().format("%y%m%d").to_string()};
    let parsed=entries.iter().map(|e|VodEntry{manifest_url:entry_url(e),duration_seconds:entry_duration(e)}).collect();
    Ok(VodMetadata{title,streamer,streamer_id,date,entries:parsed})
}

async fn complete_metadata_from_api(vod_url:&str,metadata:&mut VodMetadata,jar:&CookieJar)->Result<()> {
    if metadata.entries.iter().all(|e|!e.manifest_url.is_empty()&&e.duration_seconds>0){return Ok(());}
    let client=http_client()?; let title=title_no(vod_url)?; let cookie=jar.header_for("https://api.m.sooplive.co.kr/")?;
    let response=client.post("https://api.m.sooplive.co.kr/station/video/a/view").header(REFERER,vod_url).header(COOKIE,cookie).form(&[("nTitleNo",title.as_str()),("nApiLevel","10")]).send().await?.error_for_status()?;
    let value:Value=response.json().await?; let files=value.pointer("/data/files").and_then(Value::as_array).cloned().unwrap_or_default();
    for (idx,file) in files.iter().enumerate().take(metadata.entries.len()) {
        if metadata.entries[idx].manifest_url.is_empty(){metadata.entries[idx].manifest_url=api_file_url(file);}
        if metadata.entries[idx].duration_seconds==0{metadata.entries[idx].duration_seconds=entry_duration(file);}
    }
    Ok(())
}

async fn download_part(tools:&Tools,req:&VodDownloadRequest,cookie_file:&Path,url:&str,output:&Path,part:usize,part_count:usize,status:&Arc<RwLock<VodJobStatus>>,cancel:&AtomicBool,logs:&LogBuffer)->Result<()> {
    let mut args=vec!["--cookies".into(),cookie_file.display().to_string(),"--referer".into(),req.vod_url.clone(),"--add-header".into(),"Origin:https://vod.sooplive.com".into(),"--user-agent".into(),USER_AGENT.into(),"-f".into(),if req.quality.is_empty(){"best".into()}else{req.quality.clone()},"--continue".into(),"--fragment-retries".into(),"1".into(),"--retries".into(),"1".into(),"--abort-on-unavailable-fragments".into(),"--no-overwrites".into(),"--merge-output-format".into(),"mp4".into(),"--newline".into(),"-o".into(),output.display().to_string()];
    if let Some(ff)=&tools.ffmpeg{args.push("--ffmpeg-location".into());args.push(ff.display().to_string());}
    args.push(url.into());
    run_progress(&tools.yt_dlp,&args,part,part_count,status,cancel,logs).await?;
    if !output.is_file(){bail!("yt-dlp 완료 후 출력 파일이 없습니다.");}
    Ok(())
}

async fn merge_parts(tools:&Tools,metadata:&VodMetadata,files:&[PathBuf],output_dir:&Path,status:&Arc<RwLock<VodJobStatus>>,cancel:&AtomicBool,logs:&LogBuffer)->Result<PathBuf>{
    let ff=tools.ffmpeg.as_ref().ok_or_else(||anyhow!("ffmpeg를 찾을 수 없어 PART를 병합할 수 없습니다."))?;
    let concat=output_dir.join(format!(".soop-vod-concat-{}.txt",Uuid::new_v4().simple()));
    let lines=files.iter().map(|p|format!("file '{}'",p.to_string_lossy().replace('\\',"/").replace(''',"'\\''"))).collect::<Vec<_>>().join("\n"); fs::write(&concat,lines)?;
    let target=collision_path(output_dir,&format!("{}_{}",metadata.date,safe_name(&metadata.streamer)),".mp4")?;
    {let mut s=status.write().await;s.state="MERGING".into();s.message="선택한 PART를 병합 중…".into();}
    let args=vec!["-hide_banner".into(),"-loglevel".into(),"warning".into(),"-f".into(),"concat".into(),"-safe".into(),"0".into(),"-i".into(),concat.display().to_string(),"-c".into(),"copy".into(),"-n".into(),target.display().to_string()];
    let result=run_capture(ff,&args,cancel,logs,"ffmpeg merge").await; let _=fs::remove_file(&concat); result?;
    if fs::metadata(&target).map(|m|m.len()).unwrap_or(0)<1024*1024{let _=fs::remove_file(&target);bail!("FFmpeg 병합에 실패했습니다. 원본 PART 파일은 유지합니다.");}
    for file in files{let _=fs::remove_file(file);} Ok(target)
}

async fn run_progress(program:&Path,args:&[String],part:usize,part_count:usize,status:&Arc<RwLock<VodJobStatus>>,cancel:&AtomicBool,logs:&LogBuffer)->Result<()> {
    let mut child=Command::new(program).args(args).stdin(Stdio::null()).stdout(Stdio::piped()).stderr(Stdio::piped()).kill_on_drop(false).spawn()?;
    let stdout=child.stdout.take().unwrap(); let stderr=child.stderr.take().unwrap();
    let err_lines=Arc::new(Mutex::new(Vec::<String>::new())); let err_copy=err_lines.clone();
    tokio::spawn(async move{let mut lines=BufReader::new(stderr).lines();while let Ok(Some(line))=lines.next_line().await{let mut v=err_copy.lock().await;v.push(line);if v.len()>30{v.remove(0);}}});
    let mut lines=BufReader::new(stdout).lines(); let re=Regex::new(r"(?P<p>\d+(?:\.\d+)?)%").unwrap();
    loop {
        if cancel.load(Ordering::SeqCst){stop_child(&mut child).await;return Ok(());}
        tokio::select! {
            line=lines.next_line()=>{if let Ok(Some(line))=line{if let Some(c)=re.captures(&line){if let Ok(p)=c["p"].parse::<f64>(){let mut s=status.write().await;s.percent=p;s.current_part=part;s.part_count=part_count;s.message=format!("PART {part}: {p:.1}%");}}}}
            _=tokio::time::sleep(Duration::from_millis(250))=>{}
        }
        if let Some(exit)=child.try_wait()?{if exit.success(){return Ok(());}let detail=err_lines.lock().await.iter().rev().take(12).cloned().collect::<Vec<_>>().into_iter().rev().collect::<Vec<_>>().join(" | ");bail!("yt-dlp exit={:?}: {}",exit.code(),redact(&detail));}
    }
}

async fn run_capture(program:&Path,args:&[String],cancel:&AtomicBool,logs:&LogBuffer,label:&str)->Result<String>{
    let mut child=Command::new(program).args(args).stdin(Stdio::null()).stdout(Stdio::piped()).stderr(Stdio::piped()).kill_on_drop(false).spawn().with_context(||format!("{label} 실행 실패"))?;
    loop{if cancel.load(Ordering::SeqCst){stop_child(&mut child).await;return Ok(String::new());}if child.try_wait()?.is_some(){break;}tokio::time::sleep(Duration::from_millis(200)).await;}
    let output=child.wait_with_output().await?; if !output.status.success(){bail!("{label} 실패: {}",redact(&String::from_utf8_lossy(&output.stderr)));} let text=String::from_utf8(output.stdout).context("외부 도구 stdout UTF-8 오류")?; logs.push(format!("[VOD] {label} OK")).await; Ok(text)
}

async fn run_simple_process(program:&Path,args:&[&str],cancel:&AtomicBool,logs:&LogBuffer,label:&str)->Result<()> { let owned=args.iter().map(|s|s.to_string()).collect::<Vec<_>>();run_capture(program,&owned,cancel,logs,label).await.map(|_|()) }
async fn stop_child(child:&mut Child){if let Some(pid)=child.id(){#[cfg(windows)]{let _=Command::new("taskkill.exe").arg("/PID").arg(pid.to_string()).arg("/T").arg("/F").stdout(Stdio::null()).stderr(Stdio::null()).status().await;}#[cfg(not(windows))]{let _=child.kill().await;}}let _=child.wait().await;}

fn collect_set_cookies(jar:&mut CookieJar,response:&Response,default_domain:&str){for value in response.headers().get_all(SET_COOKIE).iter(){if let Ok(text)=value.to_str(){if let Some((pair,_))=text.split_once(';'){if let Some((name,value))=pair.split_once('='){jar.upsert(NetscapeCookie{domain:format!(".{default_domain}"),include_subdomains:true,path:"/".into(),secure:true,expires:0,name:name.trim().into(),value:value.trim().into()});}}}}}
fn collect_cloudfront_headers(jar:&mut CookieJar,response:&Response,manifest_url:&str)->Result<()> {let host=Url::parse(manifest_url)?.host_str().unwrap_or("").to_string();for value in response.headers().get_all(SET_COOKIE).iter(){if let Ok(text)=value.to_str(){if let Some((pair,_))=text.split_once(';'){if let Some((name,value))=pair.split_once('='){if name.to_ascii_lowercase().starts_with("cloudfront-"){jar.upsert(NetscapeCookie{domain:host.clone(),include_subdomains:false,path:"/".into(),secure:true,expires:0,name:name.into(),value:value.trim_matches('"').into()});}}}}}Ok(())}
fn collect_cloudfront_json(jar:&mut CookieJar,value:&Value,manifest_url:&str){let host=Url::parse(manifest_url).ok().and_then(|u|u.host_str().map(str::to_string)).unwrap_or_default();for name in CF_NAMES{let variants=[name.to_string(),name.replace('-','_'),name.trim_start_matches("CloudFront-").to_string()];for key in variants{if let Some(v)=value.pointer(&format!("/data/{key}")).and_then(Value::as_str).or_else(||value.get(&key).and_then(Value::as_str)){jar.upsert(NetscapeCookie{domain:host.clone(),include_subdomains:false,path:"/".into(),secure:true,expires:0,name:(*name).into(),value:v.into()});break;}}}}

fn analysis_view(url:&str,m:&VodMetadata,q:Vec<VodQualityOption>)->VodAnalysisView{VodAnalysisView{vod_url:url.into(),title:m.title.clone(),streamer:m.streamer.clone(),streamer_id:m.streamer_id.clone(),part_count:m.entries.len(),qualities:q,parts:m.entries.iter().enumerate().map(|(i,e)|VodPartInfo{part:i+1,duration_seconds:e.duration_seconds}).collect()}}
fn resolve_parts(requested:&[usize],count:usize)->Result<Vec<usize>>{if count==0{bail!("VOD PART를 찾지 못했습니다.");}let mut r=if requested.is_empty(){(1..=count).collect()}else{requested.to_vec()};r.sort_unstable();r.dedup();if r.iter().any(|p|*p<1||*p>count){bail!("PART는 1~{count} 범위여야 합니다.");}Ok(r)}
fn validate_url(value:&str)->Result<()> {let u=Url::parse(value).context("올바른 SOOP VOD URL이 아닙니다.")?;if u.scheme()!="https"||!u.host_str().unwrap_or("").ends_with("sooplive.com")||!Regex::new(r"/player/\d+").unwrap().is_match(u.path()){bail!("올바른 SOOP VOD HTTPS URL이 아닙니다.");}Ok(())}
fn validate_retries(v:u32)->Result<()>{if !(1..=20).contains(&v){bail!("MAX_RETRY must be between 1 and 20.");}Ok(())}
fn title_no(url:&str)->Result<String>{Regex::new(r"/player/(\d+)").unwrap().captures(url).and_then(|c|c.get(1)).map(|m|m.as_str().to_string()).ok_or_else(||anyhow!("VOD title_no를 찾지 못했습니다."))}
fn entry_url(v:&Value)->String{for key in ["url","manifest_url","manifestUrl","hls_url","hlsUrl"]{if let Some(s)=v.get(key).and_then(Value::as_str){if s.starts_with("https://")&&!Url::parse(s).ok().is_some_and(|u|u.path().starts_with("/player/")){return s.into();}}}if let Some(formats)=v.get("formats").and_then(Value::as_array){for f in formats{for key in ["manifest_url","manifestUrl","url"]{if let Some(s)=f.get(key).and_then(Value::as_str){if s.starts_with("https://"){return s.into();}}}}}String::new()}
fn api_file_url(v:&Value)->String{if let Some(s)=v.as_str(){return s.into();}for key in ["file","url","file_url","fileUrl"]{if let Some(s)=v.get(key).and_then(Value::as_str){return s.into();}}String::new()}
fn entry_duration(v:&Value)->u64{for key in ["duration","file_duration","play_time"]{if let Some(n)=v.get(key).and_then(Value::as_f64){if n>0.0{return n.round() as u64;}}if let Some(s)=v.get(key).and_then(Value::as_str){if let Ok(n)=s.parse::<f64>(){if n>0.0{return n.round() as u64;}}}}0}
fn str_field(v:&Value,k:&str)->Option<String>{v.get(k).and_then(Value::as_str).map(str::to_string).filter(|s|!s.trim().is_empty())}
fn read_ini(path:&Path)->Result<BTreeMap<String,String>>{let text=fs::read_to_string(path)?;let mut m=BTreeMap::new();for raw in text.lines(){let line=raw.trim();if line.is_empty()||line.starts_with('#'){continue;}if let Some((k,v))=line.split_once('='){m.insert(k.trim().into(),v.trim().into());}}Ok(m)}
fn resolve_tools(backend:&Path,yt:&str,ff:&str)->Result<Tools>{let vod=backend.join("vod");let yt=resolve_executable(yt,&[vod.join("yt-dlp.exe")],&["yt-dlp.exe","yt-dlp"]).ok_or_else(||anyhow!("yt-dlp를 찾을 수 없습니다."))?;let ff=resolve_executable(ff,&[vod.join("ffmpeg.exe")],&["ffmpeg.exe","ffmpeg"]);Ok(Tools{yt_dlp:yt,ffmpeg:ff})}
fn resolve_executable(config:&str,locals:&[PathBuf],commands:&[&str])->Option<PathBuf>{if !config.trim().is_empty(){let p=PathBuf::from(config);if p.is_file(){return Some(p);}}for p in locals{if p.is_file(){return Some(p.clone());}}for cmd in commands{if let Some(path)=find_on_path(cmd){return Some(path);}}None}
fn find_on_path(name:&str)->Option<PathBuf>{std::env::var_os("PATH").and_then(|p|std::env::split_paths(&p).map(|d|d.join(name)).find(|p|p.is_file()))}
fn safe_name(v:&str)->String{let mut s=v.chars().map(|c|if c.is_control()||r#"\/:*?"<>|"#.contains(c){'_'}else{c}).collect::<String>();s=s.trim().trim_end_matches(['.',' ']).chars().take(100).collect();if s.is_empty(){"UNKNOWN".into()}else{s}}
fn collision_path(dir:&Path,base:&str,ext:&str)->Result<PathBuf>{for i in 0..=9999{let name=if i==0{format!("{base}{ext}")}else{format!("{base}_{i:03}{ext}")};let p=dir.join(name);if !p.exists(){if p.to_string_lossy().chars().count()>240{bail!("VOD 전체 출력 경로가 안전 제한을 초과했습니다.");}return Ok(p);}}bail!("충돌 없는 출력 파일명을 만들지 못했습니다.")}
fn cleanup_incomplete(target:&Path){for suffix in [".part",".ytdl",".temp"]{let _=fs::remove_file(format!("{}{}",target.display(),suffix));}}
fn job_dir(backend:&Path)->Result<PathBuf>{let p=backend.join(".rust-web").join("vod").join(Uuid::new_v4().to_string());fs::create_dir_all(&p)?;Ok(p)}
fn cleanup_job_dir(path:&Path){let _=fs::remove_dir_all(path);}
fn sanitize_cookie_field(v:&str)->String{v.replace(['\t','\r','\n'],"")}
fn redact(text:&str)->String{let re=Regex::new(r"(?i)(cookie|token|signature|policy|key-pair-id|authorization)(\s*[:=]\s*)[^\s;&]+").unwrap();let s=re.replace_all(text,"$1$2***");Regex::new(r"(?i)(https?://[^?\s]+)\?[^\s]+").unwrap().replace_all(&s,"$1?[REDACTED]").to_string()}
fn http_client()->Result<Client>{Ok(Client::builder().no_proxy().http1_only().user_agent(USER_AGENT).timeout(Duration::from_secs(20)).build()?)}
async fn set_status(status:&Arc<RwLock<VodJobStatus>>,state:&str,message:&str){let mut s=status.write().await;s.state=state.into();s.message=message.into();}
async fn sleep_retry(attempt:u32,cancel:&AtomicBool){let secs=2u64.pow((attempt.saturating_sub(1)).min(4));for _ in 0..secs*4{if cancel.load(Ordering::SeqCst){break;}tokio::time::sleep(Duration::from_millis(250)).await;}}

#[cfg(test)]
mod tests{
    use super::*;
    #[test]fn part_selection_validates(){assert_eq!(resolve_parts(&[],3).unwrap(),vec![1,2,3]);assert!(resolve_parts(&[4],3).is_err());}
    #[test]fn safe_filename_replaces_reserved_chars(){assert_eq!(safe_name("a:b/c"),"a_b_c");}
    #[test]fn manifest_quality_parser_contract(){let text="#EXT-X-STREAM-INF:RESOLUTION=1920x1080\n#EXT-X-STREAM-INF:RESOLUTION=1280x720";let mut h=Regex::new(r"RESOLUTION=\d+x(?P<h>\d+)").unwrap().captures_iter(text).filter_map(|c|c.name("h")?.as_str().parse::<u32>().ok()).collect::<Vec<_>>();h.sort_unstable_by(|a,b|b.cmp(a));assert_eq!(h,vec![1080,720]);}
}
