let token=sessionStorage.getItem('soopToken')||'';
const $=id=>document.getElementById(id);
const keys=['CHECK_INTERVAL','CHANNEL_RELOAD_INTERVAL','RECORD_RETRY_INTERVAL','RECORD_STALL_TIMEOUT','RECORD_MONITOR_INTERVAL','WORKER_MAX_RETRY','MIN_FREE_SPACE_GB','OUTPUT_DIR','QUALITY','FILE_NAME_PATTERN','STREAMLINK_PATH','STREAMLINK_FALLBACK','YT_DLP_PATH','FFMPEG_PATH','SOOP_USERNAME','MASTER_QUALITY','CLOUDFLARE_WORKER_URL','LOG_ENABLED','LOG_DIR','LOG_RETENTION_DAYS'];
const liveSettingKeys=new Set(['CHECK_INTERVAL','CHANNEL_RELOAD_INTERVAL','RECORD_RETRY_INTERVAL','RECORD_STALL_TIMEOUT','RECORD_MONITOR_INTERVAL','WORKER_MAX_RETRY','MIN_FREE_SPACE_GB','OUTPUT_DIR','QUALITY','FILE_NAME_PATTERN','STREAMLINK_PATH','STREAMLINK_FALLBACK','SOOP_USERNAME','MASTER_QUALITY','CLOUDFLARE_WORKER_URL','LOG_ENABLED','LOG_DIR','LOG_RETENTION_DAYS']);
const vodToolKeys=new Set(['YT_DLP_PATH','FFMPEG_PATH']);
const labels={UNKNOWN:'확인중',OFFLINE:'오프라인',RECORDING:'녹화중',PAUSED:'현재방송 중지',DISABLED:'비활성',ERROR:'오류',LOW_DISK:'디스크 부족',STALLED:'녹화 정지',AUTH:'인증 필요',LIVE:'방송중'};
function getToken(){if(!token){token=(prompt('SOOP 관리 토큰을 입력하세요.')||'').trim();if(token)sessionStorage.setItem('soopToken',token)}return token}
async function api(path,opt={}){getToken();const h=new Headers(opt.headers||{});h.set('Authorization','Bearer '+token);if(opt.body)h.set('Content-Type','application/json');const r=await fetch(path,{...opt,headers:h});if(r.status===401){sessionStorage.removeItem('soopToken');token='';throw new Error('토큰이 올바르지 않습니다.')}const t=await r.text();const v=t?(()=>{try{return JSON.parse(t)}catch{return t}})():null;if(!r.ok)throw new Error(typeof v==='string'?v:JSON.stringify(v));return v}
function toast(s){$('toast').textContent=s;$('toast').className='show';setTimeout(()=>$('toast').className='',1800)}
function bytes(n){if(!n)return '-';const u=['B','KB','MB','GB','TB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return n.toFixed(i?1:0)+' '+u[i]}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function statusText(s){return labels[s]||s||'-'}
function runtimeRow(c){const tr=document.createElement('tr');const detail=[c.title,c.file,c.detail].filter(Boolean).map(esc).join('<br>');const klass=c.status==='RECORDING'?'ok':(c.status==='OFFLINE'||c.status==='DISABLED'?'muted':(c.status==='PAUSED'?'warn':(c.status==='ERROR'||c.status==='LOW_DISK'||c.status==='STALLED'?'bad':'')));const stopButton=c.status==='PAUSED'?'<button class="mini resume">재개</button>':(c.status==='RECORDING'?'<button class="mini danger stopOne">현재 방송 중지</button>':'');tr.innerHTML=`<td class="${klass}"><b>${esc(statusText(c.status))}</b></td><td>${esc(c.name)}</td><td class="mono">${esc(c.account)}</td><td class="smallcell">${detail||'-'}</td><td>${bytes(c.size_bytes)}</td><td><button class="mini recheck">재확인</button> ${stopButton}</td>`;tr.querySelector('.recheck').onclick=()=>channelAction(c.account,'recheck');const r=tr.querySelector('.resume');if(r)r.onclick=()=>channelAction(c.account,'resume');const s=tr.querySelector('.stopOne');if(s)s.onclick=()=>channelAction(c.account,'stop');return tr}
async function status(){try{const d=await api('/api/status');const w=d.watcher;$('watcher').textContent=w.running?'RUNNING':'STOPPED';$('watcher').className=w.running?'ok':'bad';$('engine').textContent=w.engine||'-';$('channelCount').textContent=w.channel_count??0;$('recCount').textContent=w.recording_count??0;$('offlineCount').textContent=w.offline_count??0;$('errorCount').textContent=w.error_count??0;$('backend').textContent=d.backend_dir;$('start').disabled=w.running;$('stop').disabled=!w.running;const body=$('runtime');body.replaceChildren();(w.channels||[]).forEach(c=>body.appendChild(runtimeRow(c)))}catch(e){$('watcher').textContent='ERROR'}}
async function channelAction(account,action){try{await api('/api/watcher/channel/'+encodeURIComponent(account)+'/'+action,{method:'POST'});toast('채널 명령 전달');setTimeout(status,250)}catch(e){alert(e.message)}}
async function resolveRow(tr,quiet=false){const ac=tr.querySelector('.ac').value.trim();if(!ac){if(!quiet)alert('계정 ID를 입력하세요.');return}const btn=tr.querySelector('.resolve');btn.disabled=true;btn.textContent='조회중';try{const d=await api('/api/channels/resolve/'+encodeURIComponent(ac));tr.querySelector('.nm').value=d.name;toast(`${ac} → ${d.name}`)}catch(e){if(!quiet)alert(e.message)}finally{btn.disabled=false;btn.textContent='이름조회'}}
function row(c={enabled:true,name:'',account:'',outdir:''}){const tr=document.createElement('tr');tr.innerHTML='<td><input class="en" type="checkbox"></td><td><input class="nm" placeholder="닉네임 자동조회"></td><td><div class="accountCell"><input class="ac"><button class="mini resolve" type="button">이름조회</button></div></td><td><input class="od"></td><td><button class="danger del">삭제</button></td>';tr.querySelector('.en').checked=c.enabled;tr.querySelector('.nm').value=c.name;tr.querySelector('.ac').value=c.account;tr.querySelector('.od').value=c.outdir;tr.querySelector('.del').onclick=()=>tr.remove();tr.querySelector('.resolve').onclick=()=>resolveRow(tr);tr.querySelector('.ac').addEventListener('change',()=>{if(!tr.querySelector('.nm').value.trim())resolveRow(tr,true)});return tr}
async function loadChannels(){const list=await api('/api/channels');const b=$('channels');b.replaceChildren();list.forEach(c=>b.appendChild(row(c)))}
async function saveChannels(){const rows=[...$('channels').querySelectorAll('tr')];for(const tr of rows){if(!tr.querySelector('.nm').value.trim()&&tr.querySelector('.ac').value.trim())await resolveRow(tr,false)}const list=rows.map(tr=>({enabled:tr.querySelector('.en').checked,name:tr.querySelector('.nm').value.trim(),account:tr.querySelector('.ac').value.trim(),outdir:tr.querySelector('.od').value.trim()}));await api('/api/channels',{method:'PUT',body:JSON.stringify(list)});toast('채널 저장 완료');loadChannels()}
async function loadSettings(){const [d,v]=await Promise.all([api('/api/settings'),api('/api/vod/tool-settings')]);const merged={...d.values,...v};const box=$('settings');box.replaceChildren();keys.forEach(k=>{const l=document.createElement('label');l.textContent=k;const i=document.createElement(k==='LOG_ENABLED'?'select':'input');i.dataset.key=k;if(k==='LOG_ENABLED'){i.innerHTML='<option>Y</option><option>N</option>'}i.value=merged[k]??'';l.appendChild(i);box.appendChild(l)})}
async function saveSettings(){const live={},vod={};document.querySelectorAll('[data-key]').forEach(i=>{const k=i.dataset.key,v=i.value.trim();if(liveSettingKeys.has(k))live[k]=v;else if(vodToolKeys.has(k))vod[k]=v});await api('/api/settings',{method:'PUT',body:JSON.stringify(live)});await api('/api/vod/tool-settings',{method:'PUT',body:JSON.stringify(vod)});toast('설정 저장 완료')}
function setSecretState(id,ok){const el=$(id);el.textContent=ok?'설정됨':'미설정';el.className=ok?'ok':'warn'}
async function loadSecrets(){const d=await api('/api/secrets');setSecretState('soopPasswordState',!!d.SOOP_PASSWORD);setSecretState('cloudflareKeyState',!!d.CLOUDFLARE_API_KEY)}
async function saveSecrets(){const u={SOOP_PASSWORD:$('soopPassword').value,CLOUDFLARE_API_KEY:$('cloudflareKey').value};const d=await api('/api/secrets',{method:'PUT',body:JSON.stringify(u)});$('soopPassword').value='';$('cloudflareKey').value='';setSecretState('soopPasswordState',!!d.SOOP_PASSWORD);setSecretState('cloudflareKeyState',!!d.CLOUDFLARE_API_KEY);toast('보안 설정 암호화 저장 완료')}
function parseParts(s){s=s.trim();if(!s)return[];const set=new Set();for(const raw of s.split(',')){const t=raw.trim();if(!t)continue;if(t.includes('-')){const [a,b]=t.split('-',2).map(Number);if(!Number.isInteger(a)||!Number.isInteger(b)||a<1||b<a)throw new Error('PART 형식 오류: '+t);for(let n=a;n<=b;n++)set.add(n)}else{const n=Number(t);if(!Number.isInteger(n)||n<1)throw new Error('PART 형식 오류: '+t);set.add(n)}}return [...set].sort((a,b)=>a-b)}
function vodBase(){return{vod_url:$('vodUrl').value.trim(),output_directory:$('vodOutput').value.trim(),cookie_mode:$('vodCookieMode').value,cookie_file:$('vodCookieFile').value.trim(),browser_name:$('vodBrowser').value.trim()||'firefox',yt_dlp_path:'',ffmpeg_path:'',max_retries:Number($('vodRetries').value)||5}}
async function vodAnalyze(){try{const req=vodBase();await api('/api/vod/analyze',{method:'POST',body:JSON.stringify(req)});toast('VOD 분석 시작');vodStatus()}catch(e){alert(e.message)}}
async function vodDownload(){try{const req={...vodBase(),parts:parseParts($('vodParts').value),quality:$('vodQuality').value||'best',merge:$('vodMerge').value==='Y'};await api('/api/vod/download',{method:'POST',body:JSON.stringify(req)});toast('VOD 다운로드 시작');vodStatus()}catch(e){alert(e.message)}}
async function vodCancel(){try{await api('/api/vod/cancel',{method:'POST'});toast('VOD 취소 요청');vodStatus()}catch(e){alert(e.message)}}
async function vodStatus(){try{const s=await api('/api/vod/status');$('vodState').textContent=s.state||'-';$('vodPart').textContent=`${s.current_part||0}/${s.part_count||0}`;$('vodPercent').textContent=`${Number(s.percent||0).toFixed(1)}%`;$('vodMessage').textContent=s.message||'';$('vodOutputFile').textContent=s.output_file?`완료 파일: ${s.output_file}`:'';$('vodAnalyze').disabled=!!s.running;$('vodDownload').disabled=!!s.running;$('vodCancel').disabled=!s.running;if(s.analysis){$('vodMeta').textContent=`${s.analysis.title} · ${s.analysis.streamer} · ${s.analysis.part_count} PART`;const q=$('vodQuality');const current=q.value;q.replaceChildren();(s.analysis.qualities||[]).forEach(o=>{const op=document.createElement('option');op.value=o.value;op.textContent=o.label;q.appendChild(op)});if([...q.options].some(o=>o.value===current))q.value=current;const parts=(s.analysis.parts||[]).map(p=>`P${p.part}:${p.duration_seconds||0}s`).join(' / ');if(parts)$('vodMeta').textContent+=` · ${parts}`}}catch(e){}}
async function logs(){try{const d=await api('/api/logs');const p=$('logs');p.textContent=d.lines.join('\n')||'(로그 없음)';p.scrollTop=p.scrollHeight}catch(e){}}
async function action(a){try{await api('/api/watcher/'+a,{method:'POST'});toast('Watcher '+(a==='start'?'시작':'중지'));status();logs()}catch(e){alert(e.message)}}
$('start').onclick=()=>action('start');$('stop').onclick=()=>action('stop');$('refreshStatus').onclick=status;$('add').onclick=()=>$('channels').appendChild(row());$('saveChannels').onclick=()=>saveChannels().catch(e=>alert(e.message));$('saveSettings').onclick=()=>saveSettings().catch(e=>alert(e.message));$('saveSecrets').onclick=()=>saveSecrets().catch(e=>alert(e.message));$('refreshLogs').onclick=logs;$('tokenBtn').onclick=()=>{sessionStorage.removeItem('soopToken');token='';location.reload()};$('vodAnalyze').onclick=vodAnalyze;$('vodDownload').onclick=vodDownload;$('vodCancel').onclick=vodCancel;
(async()=>{getToken();await Promise.all([status(),loadChannels(),loadSettings(),loadSecrets(),vodStatus(),logs()])})().catch(e=>alert(e.message));setInterval(status,2000);setInterval(vodStatus,1500);setInterval(logs,2000);
