let token=sessionStorage.getItem('soopToken')||'';
const $=id=>document.getElementById(id);
const keys=['CHECK_INTERVAL','CHANNEL_RELOAD_INTERVAL','RECORD_RETRY_INTERVAL','RECORD_STALL_TIMEOUT','RECORD_MONITOR_INTERVAL','WORKER_MAX_RETRY','MIN_FREE_SPACE_GB','OUTPUT_DIR','QUALITY','FILE_NAME_PATTERN','STREAMLINK_PATH','STREAMLINK_FALLBACK','YT_DLP_PATH','FFMPEG_PATH','SOOP_USERNAME','MASTER_QUALITY','CLOUDFLARE_WORKER_URL','LOG_ENABLED','LOG_DIR','LOG_RETENTION_DAYS'];
const liveSettingKeys=new Set(['CHECK_INTERVAL','CHANNEL_RELOAD_INTERVAL','RECORD_RETRY_INTERVAL','RECORD_STALL_TIMEOUT','RECORD_MONITOR_INTERVAL','WORKER_MAX_RETRY','MIN_FREE_SPACE_GB','OUTPUT_DIR','QUALITY','FILE_NAME_PATTERN','STREAMLINK_PATH','STREAMLINK_FALLBACK','SOOP_USERNAME','MASTER_QUALITY','CLOUDFLARE_WORKER_URL','LOG_ENABLED','LOG_DIR','LOG_RETENTION_DAYS']);
const importableLiveSettingKeys=new Set(['CHECK_INTERVAL','CHANNEL_RELOAD_INTERVAL','RECORD_RETRY_INTERVAL','RECORD_STALL_TIMEOUT','RECORD_MONITOR_INTERVAL','WORKER_MAX_RETRY','CONSOLE_REFRESH_INTERVAL','CONSOLE_AUTO_FORMAT','CHANNEL_NAME_WIDTH','CONSOLE_COLOR','CONSOLE_SHOW_PATH','GUI_NOTIFY_RECORD_START','GUI_NOTIFY_RECORD_FINISH','GUI_NOTIFY_WARNING','MIN_FREE_SPACE_GB','OUTPUT_DIR','QUALITY','FILE_NAME_PATTERN','STREAMLINK_PATH','STREAMLINK_FALLBACK','SOOP_USERNAME','CLOUDFLARE_WORKER_URL','MASTER_QUALITY','LOG_ENABLED','LOG_DIR','LOG_RETENTION_DAYS']);
const vodToolKeys=new Set(['YT_DLP_PATH','FFMPEG_PATH']);
const hiddenImportKeys=new Set(['SOOP_PASSWORD','CLOUDFLARE_API_KEY']);
const labels={UNKNOWN:'확인중',OFFLINE:'오프라인',RECORDING:'녹화중',PAUSED:'현재방송 중지',DISABLED:'비활성',ERROR:'오류',LOW_DISK:'디스크 부족',STALLED:'녹화 정지',AUTH:'인증 필요',PASSWORD_REQUIRED:'비밀번호 필요',LIVE:'방송중',COMPLETED:'완료',STOPPED:'중지',FAILED:'실패',INTERRUPTED:'비정상 종료',CANCELLED:'취소'};
function getToken(){if(!token){token=(prompt('SOOP 관리 토큰을 입력하세요.')||'').trim();if(token)sessionStorage.setItem('soopToken',token)}return token}
async function api(path,opt={}){getToken();const h=new Headers(opt.headers||{});h.set('Authorization','Bearer '+token);if(opt.body)h.set('Content-Type','application/json');const r=await fetch(path,{...opt,headers:h});if(r.status===401){sessionStorage.removeItem('soopToken');token='';throw new Error('토큰이 올바르지 않습니다.')}const t=await r.text();const v=t?(()=>{try{return JSON.parse(t)}catch{return t}})():null;if(!r.ok)throw new Error(typeof v==='string'?v:JSON.stringify(v));return v}
function toast(s){$('toast').textContent=s;$('toast').className='show';setTimeout(()=>$('toast').className='',1800)}
function bytes(n){if(!n)return '-';const u=['B','KB','MB','GB','TB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return n.toFixed(i?1:0)+' '+u[i]}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function statusText(s){return labels[s]||s||'-'}
function when(v){if(!v)return '-';try{return new Date(v).toLocaleString()}catch{return v}}
function duration(s){s=Number(s||0);if(!s)return '-';const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=Math.floor(s%60);return h?`${h}h ${m}m ${sec}s`:(m?`${m}m ${sec}s`:`${sec}s`)}
function normalizedLines(text){return String(text??'').replace(/^\uFEFF/,'').replace(/\r\n?/g,'\n').split('\n')}
function toolText(t){return t?.found?`OK${t.resolved?' · '+t.resolved:''}`:'미탐지'}
async function diagnostics(){try{const d=await api('/api/diagnostics');$('diagBind').textContent=d.bind||'-';$('diagSource').textContent=d.watcher_config_source||'-';$('diagLoopback').textContent=d.loopback_only?'YES':'NO';$('diagLoopback').className=d.loopback_only?'ok':'warn';$('diagDb').textContent=d.database||'-';$('diagStreamlink').textContent=toolText(d.tools?.streamlink);$('diagYtdlp').textContent=toolText(d.tools?.yt_dlp);$('diagFfmpeg').textContent=toolText(d.tools?.ffmpeg);$('diagRemote').textContent=d.loopback_only?'외부 접속 권장: Caddy가 TCP 80/443을 받고 127.0.0.1:8787로 reverse_proxy 하세요. 공유기 포워딩 대상은 PC의 LAN IPv4입니다.':'현재 SOOP 서버가 loopback 외 주소에서도 수신 중입니다. 인터넷 공개라면 127.0.0.1:8787 + Caddy 구조를 권장합니다.'}catch(e){$('diagRemote').textContent='진단 실패: '+e.message}}
function runtimeRow(c){const tr=document.createElement('tr');const detail=[c.title,c.file,c.detail].filter(Boolean).map(esc).join('<br>');const klass=c.status==='RECORDING'?'ok':(c.status==='OFFLINE'||c.status==='DISABLED'?'muted':(c.status==='PAUSED'||c.status==='PASSWORD_REQUIRED'?'warn':(c.status==='ERROR'||c.status==='LOW_DISK'||c.status==='STALLED'?'bad':'')));const stopButton=c.status==='PAUSED'?'<button class="mini resume">재개</button>':(c.status==='RECORDING'?'<button class="mini danger stopOne">현재 방송 중지</button>':(c.status==='PASSWORD_REQUIRED'?'<button class="mini streamPassword">비밀번호 입력</button>':''));tr.innerHTML=`<td class="${klass}"><b>${esc(statusText(c.status))}</b></td><td>${esc(c.name)}</td><td class="mono">${esc(c.account)}</td><td class="smallcell">${detail||'-'}</td><td>${bytes(c.size_bytes)}</td><td><button class="mini recheck">재확인</button> ${stopButton}</td>`;tr.querySelector('.recheck').onclick=()=>channelAction(c.account,'recheck');const r=tr.querySelector('.resume');if(r)r.onclick=()=>channelAction(c.account,'resume');const s=tr.querySelector('.stopOne');if(s)s.onclick=()=>channelAction(c.account,'stop');const p=tr.querySelector('.streamPassword');if(p)p.onclick=()=>channelPassword(c.account);return tr}
async function status(){try{const d=await api('/api/status');const w=d.watcher;$('watcher').textContent=w.running?'RUNNING':'STOPPED';$('watcher').className=w.running?'ok':'bad';$('engine').textContent=w.engine||'-';$('channelCount').textContent=w.channel_count??0;$('recCount').textContent=w.recording_count??0;$('offlineCount').textContent=w.offline_count??0;$('errorCount').textContent=w.error_count??0;$('backend').textContent=d.backend_dir;$('start').disabled=w.running;$('stop').disabled=!w.running;const body=$('runtime');body.replaceChildren();(w.channels||[]).forEach(c=>body.appendChild(runtimeRow(c)))}catch(e){$('watcher').textContent='ERROR'}}
async function channelAction(account,action){try{await api('/api/watcher/channel/'+encodeURIComponent(account)+'/'+action,{method:'POST'});toast('채널 명령 전달');setTimeout(status,250)}catch(e){alert(e.message)}}
async function channelPassword(account){const value=prompt('이 방송의 비밀번호를 입력하세요.\n비밀번호는 SQLite/파일에 저장되지 않고 현재 방송 동안 메모리에만 유지됩니다.');if(value===null)return;if(!value){alert('비밀번호를 입력하세요.');return}try{await api('/api/watcher/channel/'+encodeURIComponent(account)+'/password',{method:'POST',body:value});toast('방송 비밀번호 전달');setTimeout(status,250)}catch(e){alert(e.message)}}
async function resolveRow(tr,quiet=false){const ac=tr.querySelector('.ac').value.trim();if(!ac){if(!quiet)alert('계정 ID를 입력하세요.');return}const btn=tr.querySelector('.resolve');btn.disabled=true;btn.textContent='조회중';try{const d=await api('/api/channels/resolve/'+encodeURIComponent(ac));tr.querySelector('.nm').value=d.name;toast(`${ac} → ${d.name}`)}catch(e){if(!quiet)alert(e.message)}finally{btn.disabled=false;btn.textContent='이름조회'}}
function row(c={enabled:true,name:'',account:'',outdir:''}){const tr=document.createElement('tr');tr.innerHTML='<td><input class="en" type="checkbox"></td><td><input class="nm" placeholder="닉네임 자동조회"></td><td><div class="accountCell"><input class="ac"><button class="mini resolve" type="button">이름조회</button></div></td><td><input class="od"></td><td><button class="danger del">삭제</button></td>';tr.querySelector('.en').checked=c.enabled;tr.querySelector('.nm').value=c.name;tr.querySelector('.ac').value=c.account;tr.querySelector('.od').value=c.outdir;tr.querySelector('.del').onclick=()=>tr.remove();tr.querySelector('.resolve').onclick=()=>resolveRow(tr);tr.querySelector('.ac').addEventListener('change',()=>{if(!tr.querySelector('.nm').value.trim())resolveRow(tr,true)});return tr}
async function loadChannels(){const list=await api('/api/channels');const b=$('channels');b.replaceChildren();list.forEach(c=>b.appendChild(row(c)))}
async function saveChannels(){const rows=[...$('channels').querySelectorAll('tr')];for(const tr of rows){if(!tr.querySelector('.nm').value.trim()&&tr.querySelector('.ac').value.trim())await resolveRow(tr,false)}const list=rows.map(tr=>({enabled:tr.querySelector('.en').checked,name:tr.querySelector('.nm').value.trim(),account:tr.querySelector('.ac').value.trim(),outdir:tr.querySelector('.od').value.trim()}));await api('/api/channels',{method:'PUT',body:JSON.stringify(list)});toast('채널 저장 완료');loadChannels()}
function parseChannelBackup(text){const list=[];const seen=new Set();for(const raw of normalizedLines(text)){const line=raw.trim();if(!line||line.startsWith('#'))continue;const parts=raw.split('|');if(parts.length<3||parts.length>4)throw new Error('채널 백업 형식 오류: '+line);const flag=parts[0].trim().toUpperCase();if(flag!=='Y'&&flag!=='N')throw new Error('채널 사용값은 Y 또는 N이어야 합니다: '+line);const name=parts[1].trim(),account=parts[2].trim(),outdir=(parts[3]||'').trim();if(!name||!account)throw new Error('채널 이름/계정이 비어 있습니다: '+line);const dedupe=account.toLowerCase();if(seen.has(dedupe))throw new Error('중복 채널 계정: '+account);seen.add(dedupe);list.push({enabled:flag==='Y',name,account,outdir})}if(!list.length)throw new Error('복구할 채널이 없습니다. Y|NAME|ACCOUNT|OUTDIR 형식의 파일인지 확인하세요.');return list}
async function restoreChannelsFromFile(file){const list=parseChannelBackup(await file.text());if(!confirm(`${file.name}에서 ${list.length}개 채널을 찾았습니다.\n현재 SQLite 채널 목록을 이 백업으로 교체할까요?`))return;await api('/api/channels',{method:'PUT',body:JSON.stringify(list)});await loadChannels();await status();toast(`${list.length}개 채널 복구 완료`)}
async function loadSettings(){const [d,v]=await Promise.all([api('/api/settings'),api('/api/vod/tool-settings')]);const merged={...d.values,...v};const box=$('settings');box.replaceChildren();keys.forEach(k=>{const l=document.createElement('label');l.textContent=k;const i=document.createElement(k==='LOG_ENABLED'?'select':'input');i.dataset.key=k;if(k==='LOG_ENABLED'){i.innerHTML='<option>Y</option><option>N</option>'}i.value=merged[k]??'';l.appendChild(i);box.appendChild(l)})}
async function saveSettings(){const live={},vod={};document.querySelectorAll('[data-key]').forEach(i=>{const k=i.dataset.key,v=i.value.trim();if(liveSettingKeys.has(k))live[k]=v;else if(vodToolKeys.has(k))vod[k]=v});await api('/api/settings',{method:'PUT',body:JSON.stringify(live)});await api('/api/vod/tool-settings',{method:'PUT',body:JSON.stringify(vod)});toast('설정 저장 완료');diagnostics()}
function parseSettingsImport(text){const live={},vod={};let skippedSecrets=false;for(const raw of normalizedLines(text)){const line=raw.trim();if(!line||line.startsWith('#'))continue;const pos=raw.indexOf('=');if(pos<1)continue;const key=raw.slice(0,pos).trim(),value=raw.slice(pos+1).trim();if(hiddenImportKeys.has(key)){if(value)skippedSecrets=true;continue}if(importableLiveSettingKeys.has(key))live[key]=value;else if(vodToolKeys.has(key))vod[key]=value}if(!Object.keys(live).length&&!Object.keys(vod).length)throw new Error('가져올 수 있는 설정값이 없습니다. SOOP_LIVE_SETTING.ini/.bak 파일인지 확인하세요.');return{live,vod,skippedSecrets}}
async function importSettingsFromFile(file){const parsed=parseSettingsImport(await file.text());const count=Object.keys(parsed.live).length+Object.keys(parsed.vod).length;if(!confirm(`${file.name}에서 ${count}개 설정값을 찾았습니다.\n현재 SQLite 설정에 적용할까요?`))return;if(Object.keys(parsed.live).length)await api('/api/settings',{method:'PUT',body:JSON.stringify(parsed.live)});if(Object.keys(parsed.vod).length)await api('/api/vod/tool-settings',{method:'PUT',body:JSON.stringify(parsed.vod)});await loadSettings();await diagnostics();toast(`${count}개 설정 가져오기 완료`);if(parsed.skippedSecrets)alert('SOOP_PASSWORD / CLOUDFLARE_API_KEY 값은 보안을 위해 가져오지 않았습니다. 보안 설정에서 다시 입력하세요.')}
function setSecretState(id,ok){const el=$(id);el.textContent=ok?'설정됨':'미설정';el.className=ok?'ok':'warn'}
async function loadSecrets(){const d=await api('/api/secrets');setSecretState('soopPasswordState',!!d.SOOP_PASSWORD);setSecretState('cloudflareKeyState',!!d.CLOUDFLARE_API_KEY)}
async function saveSecrets(){const u={SOOP_PASSWORD:$('soopPassword').value,CLOUDFLARE_API_KEY:$('cloudflareKey').value};const d=await api('/api/secrets',{method:'PUT',body:JSON.stringify(u)});$('soopPassword').value='';$('cloudflareKey').value='';setSecretState('soopPasswordState',!!d.SOOP_PASSWORD);setSecretState('cloudflareKeyState',!!d.CLOUDFLARE_API_KEY);toast('보안 설정 암호화 저장 완료')}
function parseParts(s){s=s.trim();if(!s)return[];const set=new Set();for(const raw of s.split(',')){const t=raw.trim();if(!t)continue;if(t.includes('-')){const [a,b]=t.split('-',2).map(Number);if(!Number.isInteger(a)||!Number.isInteger(b)||a<1||b<a)throw new Error('PART 형식 오류: '+t);for(let n=a;n<=b;n++)set.add(n)}else{const n=Number(t);if(!Number.isInteger(n)||n<1)throw new Error('PART 형식 오류: '+t);set.add(n)}}return [...set].sort((a,b)=>a-b)}
function vodBase(){return{vod_url:$('vodUrl').value.trim(),output_directory:$('vodOutput').value.trim(),cookie_mode:$('vodCookieMode').value,cookie_file:$('vodCookieFile').value.trim(),browser_name:$('vodBrowser').value.trim()||'firefox',yt_dlp_path:'',ffmpeg_path:'',max_retries:Number($('vodRetries').value)||5}}
async function vodAnalyze(){try{const req=vodBase();await api('/api/vod/analyze',{method:'POST',body:JSON.stringify(req)});toast('VOD 분석 시작');vodStatus()}catch(e){alert(e.message)}}
async function vodDownload(){try{const req={...vodBase(),parts:parseParts($('vodParts').value),quality:$('vodQuality').value||'best',merge:$('vodMerge').value==='Y'};await api('/api/vod/download',{method:'POST',body:JSON.stringify(req)});toast('VOD 다운로드 시작');vodStatus()}catch(e){alert(e.message)}}
async function vodCancel(){try{await api('/api/vod/cancel',{method:'POST'});toast('VOD 취소 요청');vodStatus()}catch(e){alert(e.message)}}
async function vodStatus(){try{const s=await api('/api/vod/status');$('vodState').textContent=s.state||'-';$('vodPart').textContent=`${s.current_part||0}/${s.part_count||0}`;$('vodPercent').textContent=`${Number(s.percent||0).toFixed(1)}%`;$('vodMessage').textContent=s.message||'';$('vodOutputFile').textContent=s.output_file?`완료 파일: ${s.output_file}`:'';$('vodAnalyze').disabled=!!s.running;$('vodDownload').disabled=!!s.running;$('vodCancel').disabled=!s.running;if(s.analysis){$('vodMeta').textContent=`${s.analysis.title} · ${s.analysis.streamer} · ${s.analysis.part_count} PART`;const q=$('vodQuality');const current=q.value;q.replaceChildren();(s.analysis.qualities||[]).forEach(o=>{const op=document.createElement('option');op.value=o.value;op.textContent=o.label;q.appendChild(op)});if([...q.options].some(o=>o.value===current))q.value=current;const parts=(s.analysis.parts||[]).map(p=>`P${p.part}:${p.duration_seconds||0}s`).join(' / ');if(parts)$('vodMeta').textContent+=` · ${parts}`}}catch(e){}}
function liveHistoryRow(x){const tr=document.createElement('tr');const detail=[x.reason,x.file_path].filter(Boolean).map(esc).join('<br>');tr.innerHTML=`<td><b>${esc(statusText(x.status))}</b></td><td>${esc(x.channel_name)}<br><span class="mono">${esc(x.account)}</span></td><td>${esc(when(x.started_at))}</td><td>${esc(duration(x.duration_seconds))}</td><td>${bytes(x.size_bytes)}</td><td class="smallcell">${detail||'-'}</td>`;return tr}
function vodHistoryRow(x){const tr=document.createElement('tr');const name=[x.title,x.streamer].filter(Boolean).map(esc).join('<br>')||esc(x.vod_url);const result=[x.output_file,x.message].filter(Boolean).map(esc).join('<br>');tr.innerHTML=`<td><b>${esc(statusText(x.state))}</b></td><td>${esc(x.kind)}</td><td class="smallcell">${name}</td><td>${x.part_count||'-'}</td><td>${esc(when(x.started_at))}</td><td class="smallcell">${result||'-'}</td>`;return tr}
async function legacyHistory(){try{const d=await api('/api/history');const live=$('liveHistory'),vod=$('vodHistory');live.replaceChildren();vod.replaceChildren();(d.live||[]).forEach(x=>live.appendChild(liveHistoryRow(x)));(d.vod||[]).forEach(x=>vod.appendChild(vodHistoryRow(x)));if(!(d.live||[]).length){const tr=document.createElement('tr');tr.innerHTML='<td colspan="6" class="muted">LIVE 녹화 이력이 없습니다.</td>';live.appendChild(tr)}if(!(d.vod||[]).length){const tr=document.createElement('tr');tr.innerHTML='<td colspan="6" class="muted">VOD 작업 이력이 없습니다.</td>';vod.appendChild(tr)}}catch(e){}}
async function logs(){try{const d=await api('/api/logs');const p=$('logs');p.textContent=d.lines.join('\n')||'(로그 없음)';p.scrollTop=p.scrollHeight}catch(e){}}
async function action(a){try{await api('/api/watcher/'+a,{method:'POST'});toast('Watcher '+(a==='start'?'시작':'중지'));status();logs();legacyHistory()}catch(e){alert(e.message)}}
$('start').onclick=()=>action('start');$('stop').onclick=()=>action('stop');$('refreshStatus').onclick=status;$('refreshDiagnostics').onclick=diagnostics;$('refreshHistory').onclick=legacyHistory;$('add').onclick=()=>$('channels').appendChild(row());$('saveChannels').onclick=()=>saveChannels().catch(e=>alert(e.message));$('restoreChannels').onclick=()=>{const input=$('channelBackupFile');input.value='';input.click()};$('channelBackupFile').onchange=()=>{const file=$('channelBackupFile').files?.[0];if(file)restoreChannelsFromFile(file).catch(e=>alert(e.message))};$('saveSettings').onclick=()=>saveSettings().catch(e=>alert(e.message));$('importSettings').onclick=()=>{const input=$('settingsImportFile');input.value='';input.click()};$('settingsImportFile').onchange=()=>{const file=$('settingsImportFile').files?.[0];if(file)importSettingsFromFile(file).catch(e=>alert(e.message))};$('saveSecrets').onclick=()=>saveSecrets().catch(e=>alert(e.message));$('refreshLogs').onclick=logs;$('tokenBtn').onclick=()=>{sessionStorage.removeItem('soopToken');token='';location.reload()};$('vodAnalyze').onclick=vodAnalyze;$('vodDownload').onclick=vodDownload;$('vodCancel').onclick=vodCancel;
(async()=>{getToken();await Promise.all([status(),diagnostics(),loadChannels(),loadSettings(),loadSecrets(),vodStatus(),legacyHistory(),logs()])})().catch(e=>alert(e.message));setInterval(status,2000);setInterval(vodStatus,1500);setInterval(legacyHistory,5000);setInterval(logs,2000);