const p8State={history:null,vodTimer:null};
function p8StatusClass(s){return s==='OK'?'ok':(s==='WARN'?'warn':(s==='CRITICAL'||s==='ERROR'?'bad':''))}
function p8StorageRow(v){const tr=document.createElement('tr');const role=(v.roles||[]).map(esc).join('<br>');const paths=(v.paths||[]).map(esc).join('<br>');const detail=v.error?esc(v.error):`${bytes(v.free_bytes)} 남음 / ${bytes(v.total_bytes)} · 사용 ${Number(v.used_percent||0).toFixed(1)}%`;tr.innerHTML=`<td class="${p8StatusClass(v.status)}"><b>${esc(v.status)}</b></td><td>${role||'-'}</td><td class="smallcell mono">${paths||'-'}</td><td>${detail}</td>`;return tr}
async function p8Storage(){const body=$('p8StorageVolumes');if(!body)return;try{const d=await api('/api/storage');$('p8StorageThreshold').textContent=`${Number(d.threshold_gb||0).toFixed(1)} GB`;$('p8DbSize').textContent=bytes(d.database_size_bytes);body.replaceChildren();(d.volumes||[]).forEach(v=>body.appendChild(p8StorageRow(v)));if(!(d.volumes||[]).length){const tr=document.createElement('tr');tr.innerHTML='<td colspan="4" class="muted">저장소 정보가 없습니다.</td>';body.appendChild(tr)}}catch(e){body.innerHTML=`<tr><td colspan="4" class="bad">${esc(e.message)}</td></tr>`}}
async function p8VodStorage(){const out=$('vodOutput')?.value.trim();const box=$('p8VodStorage');if(!box)return;if(!out){box.textContent='VOD 출력 폴더를 입력하면 남은 공간을 확인합니다.';box.className='hint';return}try{const v=await api('/api/storage/check',{method:'POST',body:JSON.stringify({path:out})});box.textContent=`VOD 저장소: ${bytes(v.free_bytes)} 남음 / ${bytes(v.total_bytes)} · 사용 ${Number(v.used_percent||0).toFixed(1)}% · ${v.status}`;box.className=p8StatusClass(v.status)}catch(e){box.textContent='VOD 저장소 확인 실패: '+e.message;box.className='bad'}}
function p8HistoryUrl(){const p=new URLSearchParams();const q=$('p8HistoryQ')?.value.trim();const status=$('p8HistoryStatus')?.value.trim();const from=$('p8HistoryFrom')?.value;const to=$('p8HistoryTo')?.value;const limit=$('p8HistoryLimit')?.value||'100';if(q)p.set('q',q);if(status)p.set('status',status);if(from)p.set('from',from);if(to)p.set('to',to);p.set('limit',limit);return '/api/history?'+p.toString()}
function p8LiveRow(x){const tr=document.createElement('tr');const detail=[x.reason,x.file_path].filter(Boolean).map(esc).join('<br>');tr.innerHTML=`<td><b>${esc(statusText(x.status))}</b></td><td>${esc(x.channel_name)}<br><span class="mono">${esc(x.account)}</span></td><td>${esc(when(x.started_at))}</td><td>${esc(duration(x.duration_seconds))}</td><td>${bytes(x.size_bytes)}</td><td class="smallcell">${detail||'-'}</td>`;return tr}
function p8VodRow(x){const tr=document.createElement('tr');const name=[x.title,x.streamer].filter(Boolean).map(esc).join('<br>')||esc(x.vod_url);const result=[x.output_file,x.message].filter(Boolean).map(esc).join('<br>');tr.innerHTML=`<td><b>${esc(statusText(x.state))}</b></td><td>${esc(x.kind)}</td><td class="smallcell">${name}</td><td>${x.part_count||'-'}</td><td>${esc(when(x.started_at))}</td><td class="smallcell">${result||'-'}</td>`;return tr}
async function p8History(){try{const d=await api(p8HistoryUrl());p8State.history=d;const live=$('p8LiveHistory'),vod=$('p8VodHistory');live.replaceChildren();vod.replaceChildren();(d.live||[]).forEach(x=>live.appendChild(p8LiveRow(x)));(d.vod||[]).forEach(x=>vod.appendChild(p8VodRow(x)));if(!(d.live||[]).length){const tr=document.createElement('tr');tr.innerHTML='<td colspan="6" class="muted">조건에 맞는 LIVE 이력이 없습니다.</td>';live.appendChild(tr)}if(!(d.vod||[]).length){const tr=document.createElement('tr');tr.innerHTML='<td colspan="6" class="muted">조건에 맞는 VOD 이력이 없습니다.</td>';vod.appendChild(tr)}}catch(e){toast('History 조회 실패: '+e.message)}}
function p8CsvCell(v){const s=String(v??'').replace(/"/g,'""');return `"${s}"`}
function p8ExportCsv(){const d=p8State.history;if(!d){toast('먼저 History를 조회하세요.');return}const rows=[['type','status','name','account_or_url','started_at','duration_or_parts','size_bytes','result']];for(const x of d.live||[])rows.push(['LIVE',x.status,x.channel_name,x.account,x.started_at,x.duration_seconds,x.size_bytes,[x.reason,x.file_path].filter(Boolean).join(' | ')]);for(const x of d.vod||[])rows.push(['VOD',x.state,x.title||x.streamer,x.vod_url,x.started_at,x.part_count,'',[x.output_file,x.message].filter(Boolean).join(' | ')]);const csv='\uFEFF'+rows.map(r=>r.map(p8CsvCell).join(',')).join('\r\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`soop-history-${new Date().toISOString().slice(0,10)}.csv`;document.body.appendChild(a);a.click();URL.revokeObjectURL(a.href);a.remove()}
function p8ClearHistory(){for(const id of ['p8HistoryQ','p8HistoryStatus','p8HistoryFrom','p8HistoryTo']){const el=$(id);if(el)el.value=''}p8History()}
function p8Init(){const refresh=$('p8RefreshStorage');if(refresh)refresh.onclick=()=>{p8Storage();p8VodStorage()};const vodOut=$('vodOutput');if(vodOut){vodOut.addEventListener('change',p8VodStorage);vodOut.addEventListener('blur',p8VodStorage)}$('p8ApplyHistory').onclick=p8History;$('p8ClearHistory').onclick=p8ClearHistory;$('p8ExportHistory').onclick=p8ExportCsv;$('p8HistoryQ').addEventListener('keydown',e=>{if(e.key==='Enter')p8History()});p8Storage();p8VodStorage();p8History();setInterval(p8Storage,15000);setInterval(p8History,10000)}
p8Init();
