const p8State={history:null,vodTimer:null,appTab:'dashboard',settingsTab:'general'};
const p8SettingKeys=['CHECK_INTERVAL','CHANNEL_RELOAD_INTERVAL','RECORD_RETRY_INTERVAL','RECORD_STALL_TIMEOUT','RECORD_MONITOR_INTERVAL','WORKER_MAX_RETRY','CONSOLE_REFRESH_INTERVAL','CONSOLE_AUTO_FORMAT','CHANNEL_NAME_WIDTH','CONSOLE_COLOR','CONSOLE_SHOW_PATH','GUI_NOTIFY_RECORD_START','GUI_NOTIFY_RECORD_FINISH','GUI_NOTIFY_WARNING','MIN_FREE_SPACE_GB','OUTPUT_DIR','QUALITY','FILE_NAME_PATTERN','STREAMLINK_PATH','STREAMLINK_FALLBACK','YT_DLP_PATH','FFMPEG_PATH','SOOP_USERNAME','MASTER_QUALITY','CLOUDFLARE_WORKER_URL','LOG_ENABLED','LOG_DIR','LOG_RETENTION_DAYS'];
const p8SettingGroup={CHECK_INTERVAL:'watcher',CHANNEL_RELOAD_INTERVAL:'watcher',RECORD_RETRY_INTERVAL:'watcher',RECORD_STALL_TIMEOUT:'watcher',RECORD_MONITOR_INTERVAL:'watcher',WORKER_MAX_RETRY:'watcher',CONSOLE_REFRESH_INTERVAL:'alerts',CONSOLE_AUTO_FORMAT:'alerts',CHANNEL_NAME_WIDTH:'alerts',CONSOLE_COLOR:'alerts',CONSOLE_SHOW_PATH:'alerts',GUI_NOTIFY_RECORD_START:'alerts',GUI_NOTIFY_RECORD_FINISH:'alerts',GUI_NOTIFY_WARNING:'alerts',MIN_FREE_SPACE_GB:'general',OUTPUT_DIR:'general',QUALITY:'general',FILE_NAME_PATTERN:'general',STREAMLINK_PATH:'tools',STREAMLINK_FALLBACK:'tools',YT_DLP_PATH:'tools',FFMPEG_PATH:'tools',SOOP_USERNAME:'general',MASTER_QUALITY:'general',CLOUDFLARE_WORKER_URL:'general',LOG_ENABLED:'logs',LOG_DIR:'logs',LOG_RETENTION_DAYS:'logs'};
const p8NumberMeta={CHECK_INTERVAL:[1,86400,1],CHANNEL_RELOAD_INTERVAL:[1,3600,1],RECORD_RETRY_INTERVAL:[1,3600,1],RECORD_STALL_TIMEOUT:[10,86400,5],RECORD_MONITOR_INTERVAL:[1,3600,1],WORKER_MAX_RETRY:[0,100,1],CONSOLE_REFRESH_INTERVAL:[1,3600,1],MIN_FREE_SPACE_GB:[0,1000000,0.5],LOG_RETENTION_DAYS:[0,36500,1]};
const p8YesNo=new Set(['CONSOLE_AUTO_FORMAT','CONSOLE_COLOR','CONSOLE_SHOW_PATH','GUI_NOTIFY_RECORD_START','GUI_NOTIFY_RECORD_FINISH','GUI_NOTIFY_WARNING','LOG_ENABLED']);
const p8PathKeys=new Set(['OUTPUT_DIR','LOG_DIR','STREAMLINK_PATH','STREAMLINK_FALLBACK','YT_DLP_PATH','FFMPEG_PATH']);
function p8StatusClass(s){return s==='OK'?'ok':(s==='WARN'?'warn':(s==='CRITICAL'||s==='ERROR'?'bad':''))}
function p8SetAppTab(name,persist=true){const valid=['dashboard','channels','vod','history','settings','diagnostics'];if(!valid.includes(name))name='dashboard';p8State.appTab=name;document.querySelectorAll('[data-tab-page]').forEach(el=>el.hidden=el.dataset.tabPage!==name);document.querySelectorAll('[data-app-tab]').forEach(btn=>{const on=btn.dataset.appTab===name;btn.classList.toggle('active',on);btn.setAttribute('aria-selected',on?'true':'false')});if(persist)localStorage.setItem('soopAppTab',name);if(location.hash!=='#'+name)history.replaceState(null,'','#'+name);window.scrollTo({top:0,behavior:'instant'})}
function p8SetSettingsTab(name,persist=true){const valid=['general','watcher','tools','logs','alerts','security'];if(!valid.includes(name))name='general';p8State.settingsTab=name;document.querySelectorAll('[data-settings-tab]').forEach(btn=>{const on=btn.dataset.settingsTab===name;btn.classList.toggle('active',on);btn.setAttribute('aria-selected',on?'true':'false')});const security=name==='security';const fields=$('p8SettingsFields'),sec=$('p8SecurityPanel');if(fields)fields.hidden=security;if(sec)sec.hidden=!security;let visible=0;document.querySelectorAll('#settings label[data-setting-group]').forEach(label=>{const on=label.dataset.settingGroup===name;label.hidden=security||!on;if(on)visible++});const empty=$('p8SettingsEmpty');if(empty)empty.hidden=security||visible>0;if(persist)localStorage.setItem('soopSettingsTab',name)}
function p8InitTabs(){document.querySelectorAll('[data-app-tab]').forEach(btn=>btn.onclick=()=>p8SetAppTab(btn.dataset.appTab));document.querySelectorAll('[data-settings-tab]').forEach(btn=>btn.onclick=()=>p8SetSettingsTab(btn.dataset.settingsTab));const hash=(location.hash||'').replace(/^#/,'');const initial=['dashboard','channels','vod','history','settings','diagnostics'].includes(hash)?hash:(localStorage.getItem('soopAppTab')||'dashboard');p8SetAppTab(initial,false);p8SetSettingsTab(localStorage.getItem('soopSettingsTab')||'general',false);window.addEventListener('hashchange',()=>{const h=location.hash.replace(/^#/,'');if(['dashboard','channels','vod','history','settings','diagnostics'].includes(h))p8SetAppTab(h,false)})}
function p8SettingControl(key,value){let el;if(p8NumberMeta[key]){const [min,max,step]=p8NumberMeta[key];el=document.createElement('input');el.type='number';el.min=String(min);el.max=String(max);el.step=String(step)}else if(p8YesNo.has(key)){el=document.createElement('select');el.innerHTML='<option value="Y">켜기 (Y)</option><option value="N">끄기 (N)</option>'}else if(key==='FILE_NAME_PATTERN'){el=document.createElement('select');const known=['LEGACY','TIME_TITLE'];if(value&&!known.includes(String(value).toUpperCase())){const opt=document.createElement('option');opt.value=value;opt.textContent=`현재값: ${value}`;el.appendChild(opt)}for(const v of known){const opt=document.createElement('option');opt.value=v;opt.textContent=v==='LEGACY'?'LEGACY · 기존 형식':'TIME_TITLE · 날짜_시간_제목_채널';el.appendChild(opt)}}else{el=document.createElement('input');el.type='text'}el.dataset.key=key;el.value=value??'';if(p8PathKeys.has(key)){el.placeholder=key.includes('PATH')?'AUTO 또는 실행 파일 경로':'폴더 경로'}return el}
async function p8LoadSettingsUX(){const [d,v]=await Promise.all([api('/api/settings'),api('/api/vod/tool-settings')]);const merged={...d.values,...v};const box=$('settings');if(!box)return;box.replaceChildren();for(const key of p8SettingKeys){const label=document.createElement('label');label.dataset.settingGroup=p8SettingGroup[key]||'general';const title=document.createElement('span');title.textContent=key;label.appendChild(title);label.appendChild(p8SettingControl(key,merged[key]??''));if(p8PathKeys.has(key)){const note=document.createElement('span');note.className='hint';note.textContent='경로 선택 버튼은 로컬 Windows native picker 단계에서 추가 예정이며 현재는 직접 입력/AUTO를 사용합니다.';label.appendChild(note)}box.appendChild(label)}p8SetSettingsTab(p8State.settingsTab,false)}
function p8InstallSettingsOverride(){try{loadSettings=p8LoadSettingsUX}catch{}p8LoadSettingsUX().catch(e=>toast('설정 UI 로드 실패: '+e.message))}
function p8StorageRow(v){const tr=document.createElement('tr');const role=(v.roles||[]).map(esc).join('<br>');const paths=(v.paths||[]).map(esc).join('<br>');const detail=v.error?esc(v.error):`${bytes(v.free_bytes)} 남음 / ${bytes(v.total_bytes)} · 사용 ${Number(v.used_percent||0).toFixed(1)}%`;tr.innerHTML=`<td class="${p8StatusClass(v.status)}"><b>${esc(v.status)}</b></td><td>${role||'-'}</td><td class="smallcell mono">${paths||'-'}</td><td>${detail}</td>`;return tr}
async function p8Storage(){const body=$('p8StorageVolumes');if(!body)return;try{const d=await api('/api/storage');$('p8StorageThreshold').textContent=`${Number(d.threshold_gb||0).toFixed(1)} GB`;$('p8DbSize').textContent=bytes(d.database_size_bytes);body.replaceChildren();(d.volumes||[]).forEach(v=>body.appendChild(p8StorageRow(v)));if(!(d.volumes||[]).length){const tr=document.createElement('tr');tr.innerHTML='<td colspan="4" class="muted">저장소 정보가 없습니다.</td>';body.appendChild(tr)}}catch(e){body.innerHTML=`<tr><td colspan="4" class="bad">${esc(e.message)}</td></tr>`}}
async function p8VodStorage(){const out=$('vodOutput')?.value.trim();const box=$('p8VodStorage');if(!box)return;if(!out){box.textContent='VOD 출력 폴더를 입력하면 남은 공간을 확인합니다.';box.className='hint';return}try{const v=await api('/api/storage/check',{method:'POST',body:JSON.stringify({path:out})});box.textContent=`VOD 저장소: ${bytes(v.free_bytes)} 남음 / ${bytes(v.total_bytes)} · 사용 ${Number(v.used_percent||0).toFixed(1)}% · ${v.status}`;box.className=p8StatusClass(v.status)}catch(e){box.textContent='VOD 저장소 확인 실패: '+e.message;box.className='bad'}}
function p8HistoryUrl(){const p=new URLSearchParams();const q=$('p8HistoryQ')?.value.trim();const status=$('p8HistoryStatus')?.value.trim();const from=$('p8HistoryFrom')?.value;const to=$('p8HistoryTo')?.value;const limit=$('p8HistoryLimit')?.value||'100';if(q)p.set('q',q);if(status)p.set('status',status);if(from)p.set('from',from);if(to)p.set('to',to);p.set('limit',limit);return '/api/history?'+p.toString()}
function p8LiveRow(x){const tr=document.createElement('tr');const detail=[x.reason,x.file_path].filter(Boolean).map(esc).join('<br>');tr.innerHTML=`<td><b>${esc(statusText(x.status))}</b></td><td>${esc(x.channel_name)}<br><span class="mono">${esc(x.account)}</span></td><td>${esc(when(x.started_at))}</td><td>${esc(duration(x.duration_seconds))}</td><td>${bytes(x.size_bytes)}</td><td class="smallcell">${detail||'-'}</td>`;return tr}
function p8VodRow(x){const tr=document.createElement('tr');const name=[x.title,x.streamer].filter(Boolean).map(esc).join('<br>')||esc(x.vod_url);const result=[x.output_file,x.message].filter(Boolean).map(esc).join('<br>');tr.innerHTML=`<td><b>${esc(statusText(x.state))}</b></td><td>${esc(x.kind)}</td><td class="smallcell">${name}</td><td>${x.part_count||'-'}</td><td>${esc(when(x.started_at))}</td><td class="smallcell">${result||'-'}</td>`;return tr}
async function p8History(){try{const d=await api(p8HistoryUrl());p8State.history=d;const live=$('p8LiveHistory'),vod=$('p8VodHistory');if(!live||!vod)return;live.replaceChildren();vod.replaceChildren();(d.live||[]).forEach(x=>live.appendChild(p8LiveRow(x)));(d.vod||[]).forEach(x=>vod.appendChild(p8VodRow(x)));if(!(d.live||[]).length){const tr=document.createElement('tr');tr.innerHTML='<td colspan="6" class="muted">조건에 맞는 LIVE 이력이 없습니다.</td>';live.appendChild(tr)}if(!(d.vod||[]).length){const tr=document.createElement('tr');tr.innerHTML='<td colspan="6" class="muted">조건에 맞는 VOD 이력이 없습니다.</td>';vod.appendChild(tr)}}catch(e){toast('History 조회 실패: '+e.message)}}
function p8CsvCell(v){const s=String(v??'').replace(/"/g,'""');return `"${s}"`}
function p8ExportCsv(){const d=p8State.history;if(!d){toast('먼저 History를 조회하세요.');return}const rows=[['type','status','name','account_or_url','started_at','duration_or_parts','size_bytes','result']];for(const x of d.live||[])rows.push(['LIVE',x.status,x.channel_name,x.account,x.started_at,x.duration_seconds,x.size_bytes,[x.reason,x.file_path].filter(Boolean).join(' | ')]);for(const x of d.vod||[])rows.push(['VOD',x.state,x.title||x.streamer,x.vod_url,x.started_at,x.part_count,'',[x.output_file,x.message].filter(Boolean).join(' | ')]);const csv='\uFEFF'+rows.map(r=>r.map(p8CsvCell).join(',')).join('\r\n');const blob=new Blob([csv],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`soop-history-${new Date().toISOString().slice(0,10)}.csv`;document.body.appendChild(a);a.click();URL.revokeObjectURL(a.href);a.remove()}
function p8ClearHistory(){for(const id of ['p8HistoryQ','p8HistoryStatus','p8HistoryFrom','p8HistoryTo']){const el=$(id);if(el)el.value=''}p8History()}
function p8Init(){p8InitTabs();p8InstallSettingsOverride();const refresh=$('p8RefreshStorage');if(refresh)refresh.onclick=()=>{p8Storage();p8VodStorage()};const vodOut=$('vodOutput');if(vodOut){vodOut.addEventListener('change',p8VodStorage);vodOut.addEventListener('blur',p8VodStorage)}if($('p8ApplyHistory'))$('p8ApplyHistory').onclick=p8History;if($('p8ClearHistory'))$('p8ClearHistory').onclick=p8ClearHistory;if($('p8ExportHistory'))$('p8ExportHistory').onclick=p8ExportCsv;if($('p8HistoryQ'))$('p8HistoryQ').addEventListener('keydown',e=>{if(e.key==='Enter')p8History()});p8Storage();p8VodStorage();p8History();setInterval(p8Storage,15000);setInterval(p8History,10000)}
p8Init();
